### ISSUE TITLE
Categorías de bloques para Gobstones

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#1]
Las categorías ideales son las siguientes:

1. Comandos
   1. Comandos primitivos (Poner, Mover, Sacar, IrAlBorde, VaciarTablero, BOOM)
   1. Procedimientos Primitivos (provistos por Gobstones Web)
   1. Procedimientos
   1. Alternativas (si-entonces-sino, si-entonces, (*)switch)
   1. Repeticiones (repetir, repetir-hasta-que, (*)para-cada)
   1. Asignación (:=)
1. Expresiones
   1. Literales (colores, direcciones, booleanos, números)
   1. Expresiones primitivas (puedeMover, hayBolitas, nroBolitas)
   1. Funciones Primitivas (provistas por Gobstones)
   1. Operaciones (numéricas, relacionales, booleanas, siguiente, previo, opuesto, (*)min-max de cada tipo). ver [1]
   1. Funciones
   1. Nombres (parámetros, variables) -> Esta categoría podría no estar explícita, o bien tendría que ser sensible al contexto... (solo muestra parámetros y variables en el scope del procedimiento seleccionado, sea lo que sea "seleccionado")
1. Definiciones ver [2]
   1. Procedimientos (simples + con parámetros) ver [3]
   1. Funciones (simples + con parámetros + con procesamiento) ver [4]

(*) Los bloques marcados de esta forma no formarán parte de la primera versión de Gobstones Web por no estar dentro de las actividades del manual. En principio no hace falta implementarlos.

[1] 

* Operaciones numéricas: +, -, *, div, mod, ^
* Operaciones relacionales: ==, /=, <=, <, >=, >
* Operaciones booleanas: &&, ||, not
* Min-Max de cada tipo: minColor(), maxColor(), minDir(), maxDir(), minBool(), maxBool()

[2]

Notar que aquí Funciones y Procedimientos aparecen nuevamente. En las categorías de funciones y procedimientos sería ideal que solo estuviesen las cosas definidas, pero no el "definir". Por eso se propone tener otra categoría separada para "Definiciones".

[3]

Los procedimientos simples son los que no tienen parámetros.

[4] 

Las funciones simples son las que no tienen parámetros. Las funciones con procesamiento son las que hacen algo antes de devolver (recordar que en Gobstones _sólo se puede hacer un return al final de una función_)

Las opciones "con parámetros" y "con procesamiento" pueden ser features de la interfaz específica de la forma de definir (o sea, no tienen que estar diferenciadas, sino ser características que se usan o no, como los parámetros actuales de PilasBloques, que están siempre pero no se usan hasta después).

**Comment by asanzo** [comment]
Como esto es lo ideal, mi propuesta es que comencemos por no modificar la interfaz de parametrización ó de definición de funciones, sino que en un principio optemos por el formato de Blockly.

En un primer sprint yo pondría todas las categorías (aunque algunas queden vacías, sólo para ir planteando el terreno a futuro. Y empezaría por estos bloques, que son los más importantes:

Primer iteración: Comandos
1. Comandos
   1. Comandos primitivos (Poner, Mover, Sacar, IrAlBorde, VaciarTablero, BOOM)
   2. Procedimientos (como vienen en Blockly, con definición y uso en un mismo lugar)
   3. Alternativas (si-entonces-sino, si-entonces)
   4. Repeticiones (repetir, repetir-hasta-que)
2. Expresiones
   1. Literales (colores, direcciones, booleanos, números)

Segunda iteración: Completando expresiones
1. Comandos (nada para agregar)
2. Expresiones
   1. Sensores primitivos (puedeMover, hayBolitas, nroBolitas)
   2. Operaciones (numéricas, relacionales, booleanas, siguiente, previo, opuesto).
   3. Funciones

Recordemos que **no debe haber chequeo de tipos** para las entradas, al menos en una primera versión de Gobstones Web.

**Comment by fidel-ml** [comment]
A las categorías habría que agregar "Asociaciones"... Sería para interactive y para el switch. ¿No?
(Ya sé, no pensamos aún el switch, y yo voy a 10mil... :D).

**Comment by asanzo** [comment]
Atenti al hacer la segunda iteración que _acabo de modificar un poco la lista de categorías_ en la descripción inicial de este issue. 

* Cambié "Sensores primitivos" por "Expresiones primitivas".
* Agregué las categorías "Procedimientos Primitivos" y "Funciones Primitivas" (#17)

**Comment by asanzo** [comment]
Inicialmente, los operadores binarios +, -, >, y, o , etc. deben verse _external_:

![seleccion_020](https://cloud.githubusercontent.com/assets/5421992/21501849/43bcb76e-cc2a-11e6-895d-8aba01fc803c.png)

Y no así:

![seleccion_021](https://cloud.githubusercontent.com/assets/5421992/21501877/5f3fb69e-cc2a-11e6-8348-0846c4b63d8b.png)

(sólo con los que tienen dos inputs).

Adicionalmente, los lógicos:

*  no deben decir "y" y "o" en el dropdown, sino:
*  "y también" y "o bien"
