### ISSUE TITLE
Media not being found

### ISSUE THREAD

**Issue by luchotc** [Program-AR/gs-element-blockly#100]
https://github.com/Program-AR/gs-element-blockly/blob/80dc10890eca6e3ee98505a0b2cbc996176eced9/gs-element-blockly.html#L211

This causes the path to be relative to the calling url and the media isn't found when using it in other projects

**Comment by asanzo** [comment]
Absolutely right. The path should be delivered as a parameter to the component. ( I edited your comment to point to the permalink of the line)

**Comment by afska** [comment]
Hmm, it's already a parameter :stuck_out_tongue: (`media`), and `"../bower_components/blockly-package/media/"` is just a default value.

**Comment by afska** [comment]
I fixed the problem in mumuki-gobstones-runner using:
```
<gs-element-blockly media="https://github.com/Program-AR/blockly-package/raw/v0.0.15/media/"></gs-element-blockly>
```

so the `media` parameter is working. Closing!
