### ISSUE TITLE
Expresiones largas son incómodas

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#11]
Mail original de @fidel-ml

Cuando se construyen expresiones complicadas, la indentación es nula... Blockly muy lindo para comandos, pero para expresiones muestra la pata flaca.

Piensen en cómo queda el bloque para

```gobstones
(not hayBolitas(Azul) && not hayBolitas(Negro)) && (not hayBolitas(Rojo) && not hayBolitas(Verde))
```

todo en una sola línea violenta... :(

¿Hay alguna forma de aliviar esto?

**Comment by asanzo** [comment]
La respuesta rápida es que no podemos tocar nada de Blockly por ahora, por falta de tiempo. Me gustaría cajonear esto hasta tener cancha.

Por otro lado, una rápida googleada no me trajo nada al respecto, hay que investigarlo un poquito.

**Comment by fidel-ml** [comment]
Se cajonea un ratito... A mí se me ocurrió que podría haber un "y" horizontal y otro "y" vertical (y lo mismo para los demás operadores).

**Comment by asanzo** [comment]
Eso técnicamente es factible. 

Pedagógicamente.... No sé.  Creo que me gusta la idea de que "hacia abajo" son comandos y "hacia la derecha" son expresiones. Aunque quizás en algún momento el pibe lo sienta necesario.

Esperemos a probar con pibes.

**Comment by fidel-ml** [comment]
El tema es que yo espero construir expresiones con cierta complejidad, y
tener que leerlas hacia la derecha lléndose 3 pantallas es un garrón.
Además, los temas de parentización pesan.
Claramente hay que buscar una forma más razonable de conseguir hacer
expresiones... (Esta gente imperativa, que no piensa en las expresiones...
:D).
FF

2016-12-26 14:22 GMT-03:00 asanzo <notifications@github.com>:

**Comment by miguelgarcia** [comment]
Podemos hacer que al generar el código el bloque expr1 AND expr2 haga esto :
Si len(expr1) + len(expr2) + 2 > 80: escupir expr1 && \n expr2
Si no, escupir expr1 && expr2

Otra alternativa es, al finalizar la generación de código y antes de devoverlo pasar el resultado por alguna función que se encargue de ponerlo lindo.

**Comment by fidel-ml** [comment]
El tema no es en texto, sino en lo que se vé en la interfaz de bloques!

2016-12-26 14:51 GMT-03:00 Miguel Garcia <notifications@github.com>:

**Comment by asanzo** [comment]
Se solucionaría con #20
