### ISSUE TITLE
CamelCase en los nombres generados

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#13]
Hoy los nombres de los procedimientos se generan con snake case:

Nombre_del_proc

Deberían generarse con CamelCase:

NombreDelProc

**Comment by miguelgarcia** [comment]
@asanzo te referís a los nombres en el código que se genera o en la forma de especificar un procedimiento primitivo ? Esto está relacionado a #31, no ?

**Comment by asanzo** [comment]
@miguelgarcia expliqué re mal, perdón.

Tiene que ver con los **espacios** que hay en el nombre del procedimiento:

![seleccion_096](https://cloud.githubusercontent.com/assets/5421992/22941578/cf2582ca-f2c4-11e6-8432-a251703f8274.png)

En general, las reglas en Gobstones son:

* No se usan guiones bajos, salvo únicamente para los procedimientos primitivos (eso lo corregiste perfecto en el issue #31 , ahora está bien). 
* Los comandos (todos, incluyendo procedimientos del usuario) se escriben en `PascalCase`.
* Las funciones (tanto las primitivas, como las del usuario) se escriben en `camelCase`. Salvo los literales, esto es regla general para todas las expresiones. Hoy por ejemplo las expresiones primitivas que hay en el toolbox deberían comenzar con minúscula.

Cualquier cosa avisame :) Perdón por la explicación pobre de arriba.

**Comment by asanzo** [comment]
Ahora que lo pienso mejor, quizás podemos patear este problema hasta cuando tengamos nuestra propia definición de procedimiento, porque estoy viendo que vas a necesitar tocar el procedure original. Ahora mando un mail.

**Comment by miguelgarcia** [comment]
Tendría que tocar nuestro generator. Puedo hacer que cuando genera el nombre de procedimiento hacer_algo_con genere HacerAlgoCon, eso no debería llevar mucho. 
  Si hace falta validarlo desde la UI, entonces si, tenemos que investigar

**Comment by asanzo** [comment]
Tenes razón!  Adelante con el generator!
