### ISSUE TITLE
Procedimientos Primitivos

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#17]
Del lado de Gobstones Web, al definir una actividad, probablemente existan _procedimientos que vengan ya programados gratis, y que no queremos que se vea el código_, **pero sí deben poderse usar**.

Entonces, en el toolbox tienen que aparecer los bloques que representan _la llamada_ a esos procedimientos.

Por ejemplo, si me dicen que tengo que mostrar en el toolbox los procedimientos primitivos ["HacerFlor","PlantarGranja"] entonces en el toolbox aparecerán en la categoría "Procedimientos Primitivos" dos bloques: 
![seleccion_026](https://cloud.githubusercontent.com/assets/5421992/21573587/0b127118-cec5-11e6-8401-c76860a938c8.png) y ![seleccion_027](https://cloud.githubusercontent.com/assets/5421992/21573598/28512602-cec5-11e6-928a-b6b89afef0e4.png)

que cuando se usen deben escupir `HacerFlor()` y `PlantarGranja()` respectivamente.

-----

Dicho esto, algo importante: pueden venir con parámetros. En este caso, se deberán reemplazar los _guiones bajos_ por _agujeros_ para poner los parámetros.

Por ejemplo, si viene la lista ["Poner_Bolitas", "Poner_FloresAl_"] debe producir los siguientes bloques:
![seleccion_024](https://cloud.githubusercontent.com/assets/5421992/21573561/adccfaf0-cec4-11e6-87f1-9a731e53691b.png) y ![seleccion_025](https://cloud.githubusercontent.com/assets/5421992/21573577/dc6c6ada-cec4-11e6-8cef-5e29f9973fbb.png)

Y deben  escupir `Poner_Bolitas(<valorcorrespondiente>)` y `Poner_FloresAl_(<valorcorrespondiente>,<elotrovalor>)` respectivamente.

**Comment by asanzo** [comment]
@faloi  pegale un vistazo a esto.

**Comment by faloi** [comment]
Clarísimo para mí, es exactamente lo que queremos. Quizás agregaría que cada vez que "se llame al método que los configura" se tienen que pisar, porque puede (y va a) pasar que un pibe cambie de actividad y entonces haya otros procedimientos primitivos, o incluso ninguno.

@rodri042, ¿algo que quieras agregar?
