### ISSUE TITLE
Guardar solución

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#21]
Que el componente provea la posibilidad de obtener el workspace para que Gobstones Web se lo guarde

**Comment by afska** [comment]
@asanzo Podrán publicar una versión de bower con este cambio así puedo avanzar integrándolo?
Saben si esto resuelve #40?

Gracias :)

**Comment by miguelgarcia** [comment]
Hola @rodri042 debería estar resuelto #21 y #40 en la versión 0.1.2
