### ISSUE TITLE
Pensar Interfaces del componente

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#23]
Hay varios features que impactan directamente en la interfaz del componente gs-element-blockly con el resto de la app (Gobstones Web) y muchos **tienen cosas en común** (como que requieren pasar listas de bloques, ó conjuntos de bloques para el workspace, etc).

Además, una vez definidas las interfaces el equipo de Gobstones Web podrá trabajar **paralelamente**

**Entonces**

Deberíamos definir interfaces para los siguientes issues:

* #21 Obtener bloques del workspace - **método `generateCode()`**
  * Entra: Nada.
  * Sale: String que representa todo el estado del workspace.
  * Qué cambia: Nada.
* #22 Planchar bloques al workspace (opuesto al anterior) - **propiedad `workspaceXML`** (falta implementar)
  * Entra: String que representa el estado del workspace.
  * Sale: Nada.
  * Qué cambia: se **reemplaza** el contenido actual del workspace por lo que vino.
* #18 Agregar bloques sin pisar - **método `appendBlocksToWorkspace(xml)`** (falta implementar)
  * Entra: String que representa el estado del workspace.
  * Sale: Nada.
  * Qué cambia: se **agrega** al contenido actual del workspace lo que vino (descartando el program si es que viene).
* #19 Solución Inicial Inmóvil - **????**
  * Entra: String que representa bloques del workspace
  * Sale: Nada.
  * Qué cambia: Aparecen esos bloques en el workspace, **sin posibilidad de modificación**.
* #6 Configuración inicial del toolbox. - **propiedad `toolbox`**
  * Entra: lista de ids de bloques visibles, y lista de ids de bloques deshabilitados.
  * Sale: nada.
  * Qué cambia: El toolbox debe mostrar sólo las categorías que tengan bloques visibles. Los bloques deshabilitados no pueden sacarse del toolbox.
* #17 Procedimientos primitivos al toolbox - **propiedad `primitiveProcedures`**
  * Entra: lista de nombres de procedimientos.
  * Sale: Nada
  * Qué cambia: El toolbox agrega 1 bloque nuevo por cada ítem de la lista.

**Comment by miguelgarcia** [comment]
Hice una propuesta de interfaz en el commit https://github.com/Program-AR/gs-element-blockly/commit/846ffa319e4ddb2ddbf44ee2fe3806bd469d3af6

**Comment by asanzo** [comment]
Gracias, Mike!!!

Ahí actualicé el comment inicial haciendo referencia a la nueva interfaz. Ojo que falta especificar la interfaz #19 (ahí arriba puse **????** para marcarlo). La propiedad `workspaceCanEdit` no resuelve el problema, lo que se busca es _fijar ciertos bloques iniciales_. Esos no se podrán modificar (quedarán quietos como hoy el bloque "programa"), el resto de los bloques que quiera agregar el usuario sí se podrán modificar.
Cuando vuelvas de tus vacas lo vemos :smile: 

@rodri042 @faloi Ahí tienen para chusmear. ¿Qué les parece esta idea de interfaz?

**Comment by afska** [comment]
Ahí lo pude ver.

Me parece bien! Para trabajar paralelamente algo re re importante es [este issue](https://github.com/Program-AR/gs-element-blockly/issues/25). Porfa, si tienen un rato chusméenlo, si solucionamos este tema yo ya puedo ir avanzando para meterlo dentro de GW.

Gracias! :smiley:

**Comment by afska** [comment]
Tengo una más: método `clear()` para limpiar el workspace (la usaría para alternar entre biblioteca y código principal para cuando esta primera todavía no tiene nada).
