### ISSUE TITLE
Formas de organizar código (colapsar bloque)

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#24]
Propuesto por Fidel:

Tenemos que resolver el problema de que el pibe maneje en el workspace **mucho código**

> Otra cosa más ambiciosa que se me ocurre es que las definiciones de
procedimentos se puedan "foldear". O sea, esconder el bloque que lo
define y quedar en una línea (de manera similar al "Edit" en
Code.org).

> [otra forma] que se me ocurre (que no afecta a los bloques) es
tener "páginas" de canvas, o sea, varios canvas diferentes donde puedo
poner diferentes cosas. (Al estilo las hojas de una planilla de
cálculo).

> Posta, necesitamos algunas maneras de organizar el código que resulte,
porque va a ser muy duro si no...

**Comment by asanzo** [comment]
- Otra idea, es que pueda haber ifelses que ocupen una sola línea. ¿quizás hacer eso con cualquier input statement? ¿Habrá un feature request en blockly?

**Comment by fidel-ml** [comment]
Yo creo, hoy, después de haber hecho varios programas medianos, que lo de "DeseableNoObligatorio" es demasiado suave... Es muy importante que el código se pueda organizar para entenderlo. 

Por otra parte, no entendí lo de los ifelses y cómo impacta en esto...

**Comment by asanzo** [comment]
Es un comentario que había puesto porque me habías tirado la idea de que el si/sino no ocupara tanto espacio a lo alto y sí a lo largo.... Estoy desestimando ese comment por ahora

**Comment by asanzo** [comment]
Duplicado #76
