### ISSUE TITLE
No funciona dentro de otro componente Polymer

### ISSUE THREAD

**Issue by afska** [Program-AR/gs-element-blockly#25]
Relacionado a https://github.com/Program-AR/gs-element-blockly/issues/7

Me metí en las entrañas de `bower_components` y cambié las cosas que puse [por aquí](https://github.com/Program-AR/gs-element-blockly/issues/7#issuecomment-271497546) pa' salir andando. Hay un tema:

Al usar el componente dentro de otro (cosa que va a ser necesaria en Gobstones Web), Polymer mete los elementos en un Local DOM que es privado, y cosas como `document.getElementById("toolbox")` no funcionan. Para hacer esas cosas, el fwk te deja hacer algo como `this.$$("#toolbox")` que es equivalente pero accede directamente al DOM privado del elemento, lo que garantiza que siempre ande y accedas a donde querés. Hecho ese cambio [acá](https://github.com/Program-AR/gs-element-blockly/blob/dev/app/gs-element-blockly.html#L134) y [acá](https://github.com/Program-AR/gs-element-blockly/blob/dev/app/gs-element-blockly.html#L220) llegué a un callejón sin salida en donde ya no tengo más posibilidad de cambiar nada: **el código de Blockly**.

O sea, Blockly rompe porque no puede encontrar *qué-se-yo-cuál* elemento con `document.getElementById` :cry: 

![screenshot4](https://cloud.githubusercontent.com/assets/1631752/21797389/63d5e23a-d717-11e6-986d-fdf2d80c3032.png)

Esa prueba que hice la pueden encontrar en https://github.com/rodri042/prueba-blockly/blob/master/prueba-con-local-dom.html

PD: Parece que este es un problema común. El Blockly "vainilla" no parece soportar funcionar dentro de webcomponents. Links que pueden ser útiles:

Discusión al respecto: https://groups.google.com/forum/#!topic/blockly/4u-Ay7Uk7NY
Flaquito que hizo un fork y adaptó el código para arreglarlo: https://github.com/eclecticdave/blockly/commits/webcomponent
Componente genérico de Blockly (tal vez sirva para mirar cómo está hecho): https://github.com/gmp26/blockly-element

**Comment by afska** [comment]
@asanzo

**Comment by asanzo** [comment]
@rodri042 Mike se encarga cuando vuelva de vacas, perdón  por el cuelgue :$

**Comment by asanzo** [comment]
@miguelgarcia yo resolvería primero el #7.

Estuve mirando esto, leyendo con más amor lo que mandó Rodri, y no me gusta nada. Estuvimos escapando lo más posible a hacer un fork de blockly, porque básicamente lo que está pasando con todos los proyectos que usan blockly es que tienen su propio fork, que deben mantener ellos y los merges con los updates de Blockly no son triviales.

Qué terrible lo rígido que es Blockly.

De lo que puso Rodri, veo que este commit del proyecto de un chabón es el que hace la magia:
https://github.com/eclecticdave/blockly/commit/223ad95a1654df21b08f9319e56c6e2cd8450722

Sin embargo, me gustaría escaparle a esto.

@rodri042 , @miguelgarcia 
¿Qué tan sucio les parece diseñar gs-element-blockly para que tenga dentro un iframe, parecido a lo que hicimos en pilas-bloques con pilas-web? No tengo bien en claro pros y contras y me gustaría charlarlo.

**Comment by afska** [comment]
@asanzo 

Qué raro que el flaco este del fork no le tiró un PR a blockly con eso, es medio heavy que no ande, aparte de que son dos cosas de Google XD

> ¿Qué tan sucio les parece diseñar gs-element-blockly para que tenga dentro un iframe, parecido a lo que hicimos en pilas-bloques con pilas-web? No tengo bien en claro pros y contras y me gustaría charlarlo.

Hmm, de movida se me ocurre que vamos a tener problemas para redimensionarlo al tamaño del editor. Esto va a estar en https://gobstones.github.io/gobstones-web/#/blocks reemplazando al editor ace, y uno de los requerimientos es que se adapte cuando el usuario resizee los paneles.

**Comment by asanzo** [comment]
Hola de nuevo!

En realidad, hoy tenemos en otro proyecto un problema parecido resuelto metiendo dentro de un iframe, y el resize funcionando. Acá Hugo y Mike van a saber mejor que yo que no estoy metido en eso.

Tiro otro proyecto que encontré: [Blocklymer](https://github.com/rraallvv/blocklymer). Parece que el muchacho encontró una forma de meter Blockly directamente (sin forks ni iframes). La joda parecería estar acá en su archivo [blockly-workspace.html](https://github.com/rraallvv/blocklymer/blob/master/blockly-workspace.html).  Chusmeemos por ahí también.

P.D.: Por cierto, me acabo de dar cuenta de que los tests estallan por este mismo problema.

**Comment by miguelgarcia** [comment]
Hola @rodri042 , hice cambios en gs-element-blockly, publique la versión 0.1.1, y en el proyecto de prueba de Alf https://github.com/asanzo/prueba-blockly .

Está funcionando prueba-con-local-dom.html, podrás pegarle una mirada a ver si con eso alcanzaría para meter el componente dentro de otro ?

Saludos !

**Comment by afska** [comment]
Dale. A la noche lo miro!

Saludos!

**Comment by afska** [comment]
@miguelgarcia Ahí lo probé.

Funciona en mi repo de prueba, pero no en GW :cry: 
![screenshot2](https://cloud.githubusercontent.com/assets/1631752/22568903/3c06ac14-e99e-11e6-92cb-ec91470ebc62.png)

No lo pude reproducir en un entorno más controlado, podés probarlo con https://github.com/gobstones/gobstones-web en la branch `prueba-blockly".
Ahí si hacés:
```
npm install & bower install
gulp serve
```

en http://localhost:5000/#/blocks figura el error ese en la consola.

**Comment by miguelgarcia** [comment]
Por lo que ví, el problema es que por un error anterior el componente padre no se attachea al documento aparentemente. Si comento todo el código del método ready de gobstones-editor, entonces blockly se muestra bien.
   Les parece limpiar el código de gobstones-web de otros errores antes de integrar blockly ? así achicamos las fuentes de problemas.

**Comment by afska** [comment]
Tenés mucha razón, me apresuré y al ver tipo de error que tiraba, me
pareció que era parte del mismo problema.

Está andando!
Por mí podemos dar por cerrado el issue. Si encuentro alguna otra cosa les
chiflo por otro lado.

Gracias a ambos!

**Comment by miguelgarcia** [comment]
Que bueno @rodri042 :) 

Dale cerramos este issue y vamos levantando otros con lo que surja de la integración

Un golazo no tener que forkear blockly ni meter el iframe
