### ISSUE TITLE
Procedure call debería tener parámetros inline

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#34]
![seleccion_073](https://cloud.githubusercontent.com/assets/5421992/22519107/e9433d6e-e88d-11e6-98e6-b020c68f3805.png)

**Comment by asanzo** [comment]
@faloi @fidel-ml  
Discutimos con Fidel que pueden ser inline ó no, ¿ debería ser igual a los procedimientos primitivos y las primitivas? Pros? cons?

**Comment by faloi** [comment]
A mí el inline me resulta muy simpático, y sigue con la idea de _sentence case_ que venimos laburando: los nombres de procedimientos y funciones son exactamente como los diríamos en español.

Personalmente, me gustaría que seamos consistentes con la decisión que tomamos para las primitivas. Dicho eso, si en términos de desarrollo es muy complejo y tenemos otras prioridades, lo dejaría para una próxima iteración; no me parece una funcionalidad bloqueante.

**Comment by fidel-ml** [comment]
El problema más importante de hacerlo con sentenceCase es que todos los
parámetros quedan al final: no se puede lograr que sean como en Scratch,
donde los parámetros quedan en medio. Y eso hace que sea molestoso.

El problema más importante de hacerlo no-inline es que no es homogéneo con
los comandos y procedimientos primitivos, dificultando la visión de que el
programador define nuevos comandos.
Otro problema es que tenemos que cambiar el nombre de unos cuantos
procedimientos en el manual, porque están pensados para sentenceCase...

La decisión es nuestra. Hoy, si no tocamos nada, queda todo lo primitivo
inline, y lo no primitivo como no inline.
FF


2017-04-18 14:51 GMT-03:00 Federico Aloi <notifications@github.com>:
