### ISSUE TITLE
Comenzando con Tests

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#35]
Estaría bueno tener algunos tests sobre las funcionalidades más importantes.

1. En principio, estaría bueno tener un mini framework simple, como la función "testPilas" de Pilas Bloques, que permita pasarle dos strings: un XML -bloques- y un código gobsontes, y haga un assert de que el código que produzcan esos bloques sea el pasado por parámetro.

2. Después, con eso hacer algunas pruebas:
 a. Un test por cada comando y literal (sin agujeros). Por ejemplo, que ![seleccion_075](https://cloud.githubusercontent.com/assets/5421992/22603489/65064df8-ea26-11e6-82ad-1e7215e35e4e.png) ande bien, escupiendo `Poner(Rojo)`
 b. Un test que pruebe que un procedimiento primitivo con parámetros al medio, y final, escupe la llamada correspondiente, tipo Poner_FloresAl_ que ande bien.
 c. Ídem pero sin parámetros.
 d. Algo más de integración, que incluya un programa con procedimientos y primitivas.
3. Hacer este trabajo también con tests sobre la interfaz: Debería haber algún test como mínimo para cada uno de los métodos y propiedades expuestos por el componente gs-element-blockly (por ejemplo, la propiedad `toolbox` y el método `appendBlocksToWorkspace(xml)`).

En realidad esos son los que se me ocurre que pueden salir rápido y testear más o menos íntegramente lo que tenemos. Bienvenidas ideas :)

Yo los iría agregando a medida que se van resolviendo los issues que cargueé recientemente con correcciones a algunos bloques. (Por ejemplo issues #30 #31 #32 #33 )

**Comment by miguelgarcia** [comment]
Integramos travis ?

**Comment by hugoruscitti** [comment]
Puede ser útil usar travis.ci como tenemos en Program-Ar/pilas-bloques y tal vez surge.sh para deploys automáticos (https://surge.sh/help/integrating-with-travis-ci)

cc: @asanzo  @miguelgarcia
