### ISSUE TITLE
Falta categoría y Bloque "Asignación"

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#37]
La última subcategoría de Comandos debe ser Asignación.

El bloque debe verse así:
![seleccion_077](https://cloud.githubusercontent.com/assets/5421992/22653793/51454ac2-ec69-11e6-93c1-5d15a13c0179.png)

y al llenarse así:
![seleccion_078](https://cloud.githubusercontent.com/assets/5421992/22653913/c69a65dc-ec69-11e6-8f4f-a7c1bd02610a.png)

debe producir:

```gobstones
cantPalomas := nroBolitas(Rojo)
```

Como ayuda, pego un JSON posible:

```json
{
  "type": "asignacion",
  "message0": "%1 %2 := %3 %4",
  "args0": [
    {
      "type": "field_input",
      "name": "varName",
      "text": "nombre de variable"
    },
    {
      "type": "input_dummy"
    },
    {
      "type": "input_dummy"
    },
    {
      "type": "input_value",
      "name": "varValue"
    }
  ],
  "inputsInline": true,
  "previousStatement": null,
  "nextStatement": null,
  "colour": 230,
  "tooltip": "",
  "helpUrl": ""
}
```

y un posible generator:

```javascript
Blockly.GobstonesLanguage['asignacion'] = function(block) {
  var varName = block.getFieldValue('varName');
  var varValue = Blockly.JavaScript.valueToCode(block, 'varValue', Blockly.JavaScript.ORDER_ATOMIC);
  return varName + ' := ' + varValue;
};
```

**Comment by asanzo** [comment]
Comenzando a jugar en [feature/variables](https://github.com/Program-AR/gs-element-blockly/tree/feature/variables)

**Comment by miguelgarcia** [comment]
Ver https://github.com/Program-AR/gs-element-blockly/commit/11e152a45f395c7821b7c515d57ed4945d2ce399

Como hacemos el getter de variables ? botón derecho sobre la asignación y que muestre solo las del contexto ?!

**Comment by asanzo** [comment]
Creo que podemos olvidarnos del contexto por ahora, mientras tengamos estos procedimientos de porquería :P .

Con que funcione el botón derecho sobre la asignación somos felices. O sea, al hacer click sobre este bloque:
![seleccion_077](https://cloud.githubusercontent.com/assets/5421992/22653793/51454ac2-ec69-11e6-93c1-5d15a13c0179.png)

Debe aparecer un context menu mostrando:
![seleccion_122](https://cloud.githubusercontent.com/assets/5421992/23322289/fa06e1aa-fac1-11e6-8e99-c923fc8e125e.png)

@miguelgarcia , para que veas qué tocó Fede Sawady para llegar a lograr algo parecido: tenés que buscar las apariciones de `generateGetParamOption` [en blocks/procedures.js](https://github.com/Program-AR/blockly/blob/master/blocks/procedures.js) . La papa es el método `customContextMenu` del bloque. Lo que hizo Fede fue que se viera el svg del caller, re monono:

![seleccion_123](https://cloud.githubusercontent.com/assets/5421992/23322354/4496faac-fac2-11e6-8108-68fb462cf6c7.png)

**Comment by fidel-ml** [comment]
Si quieren ir en orden, para esta parte prefiero definición de funciones a asignación...
La asignación aparece al final del capítulo 8, justo antes de interactive en el capítulo 9.
En cambio funciones aparece en el capítulo 4.
