### ISSUE TITLE
No anda en chrome 47

### ISSUE THREAD

**Issue by afska** [Program-AR/gs-element-blockly#41]
Version 47.0.2526.106 (64-bit)

El error es algo así como:
**Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode**

¿Están usando algo para compilar de ES6 a ES5?

**Comment by miguelgarcia** [comment]
@rodri042 Hola, no estamos usando nada para compilar de ES6 a ES5, pero usamos chromium 55 o mayor y firefox 45 o mayor para los test.

Qué browsers apuntan a soportar con GW ?

**Comment by afska** [comment]
@fidel-ml, dice Fede que definas esto con la Fundación. Habría que ver qué versión viene en las máquinas de Conectar Igualdad

**Comment by fidel-ml** [comment]
¿Qué cosa exactamente? No entiendo qué es lo que tengo que definir...

**Comment by afska** [comment]
Desde qué versiones browsers queremos (o necesitamos) soportar.

2017-02-15 17:43 GMT-03:00 fidel-ml <notifications@github.com>:
