### ISSUE TITLE
blockly-package no carga assets en gh-pages

### ISSUE THREAD

**Issue by afska** [Program-AR/gs-element-blockly#43]
https://program-ar.github.io/gs-element-blockly/components/gs-element-blockly/

Si van al **demo** se ve:
![screenshot1](https://cloud.githubusercontent.com/assets/1631752/22667797/f9fa7ef0-ecc6-11e6-88a3-d4776fa63b8c.png)

Me pasó lo mismo cuando deployé la primera integración con GW: http://gobstones.github.io/gobstones-web/#/blocks (el tachito de basura no se ve y faltan los sonidos).

Por lo que ví es un tema (de vuelta) con la ruta a `bower_components` pero esta vez parece culpa de **blockly-package**

**Comment by asanzo** [comment]
@rodri042 @miguelgarcia 

En la versión 0.2.3 (que ya pueden instalarse por bower) corregí el problema en el demo:

https://program-ar.github.io/gs-element-blockly/components/gs-element-blockly/

![seleccion_126](https://cloud.githubusercontent.com/assets/5421992/23568532/a4a51f42-0039-11e7-968a-d1a571cb438b.png)

Pero descubrí que la prueba de @rodri042 dejó de funcionar.

El commit que lo arregla es este:

https://github.com/Program-AR/gs-element-blockly/commit/833d0b9f49cfb0a3411fc8edd8a36d4315adb547

No sé qué escribir en esa línea para que funcione tanto en el demo como en la prueba de rodri.

**Comment by miguelgarcia** [comment]
Corregí el path del media en https://github.com/Program-AR/gs-element-blockly/commit/3764ce42f27f81f029a86e0d7986cb2540895896

**Comment by asanzo** [comment]
Hola, Mike, perdón que te reabra, pero eso ya lo había intentado, y tiene el problema de que deja de andar en nuestro demo: https://program-ar.github.io/gs-element-blockly/components/gs-element-blockly/

![seleccion_170](https://cloud.githubusercontent.com/assets/5421992/24876523/6827e892-1e02-11e7-9be8-4f46075094dd.png)

(recordá que para deployar el demo tenés que hacer  ./deploy-gh-pages.sh )

Perdón, me expliqué mal yo. El problema a resolver es que ande en ambos lados: tanto en nuestro demo como en gobstonesweb. No creo que sea la primera vez que a alguien le pasa esto con assets de un componente. Y estamos deployando el demo de la forma que recomienda Polymer, así que tiene que estar resuelto ese problema.

**Comment by miguelgarcia** [comment]
Creo que ya se que pasa, el path del media se está generando relativo a la
página y no al componente, entonces depende de donde se use falla.

Los js de blockly se cargan bien porque no se cargan dinamicamente, son
tags <script> fijos.

Voy a buscarle una solución, les parece agregarle un atributo al componente
que sea media="..." y que eso se le pase a blockly ?

Miguel Angel Garcia

2017-04-10 15:33 GMT-03:00 asanzo <notifications@github.com>:

**Comment by asanzo** [comment]
Pregunta de newbie: ¿No puedo obtener la dirección del componente, para poder setear el media relativo a donde está el componente?

Me pregunto si alguno de los proyectos que chusmeaste al armar este element por primera vez no solucionaba ya este problema.

Si no encontrás nada, hagamos como decís, pero me gustaría agotar un poquito las posibilidades. 

Eso sí, si no te lo pasan el atributo media, hacé porfa que el default sea para que le funcione a Rodri.
Y desde el demo nosotros deberíamos setearle uno.

¿Tiene sentido eso? Así Rodri no tiene que tocar nada y ya le anda.

GRACIAS MIKE!!!

**Comment by miguelgarcia** [comment]
Dale, hagamos así, investigo si hay forma de conocer el location de
bower_components en dinamicamente y si no agregamos el atributo media que
por default funcione para gobstones web.

Miguel Angel Garcia

2017-04-10 17:09 GMT-03:00 asanzo <notifications@github.com>:

**Comment by miguelgarcia** [comment]
Agregue el atributo media, por default va a funcionar como lo en gobstones web. Ya agregue en la demo los cambios para que funcione también en github pages
