### ISSUE TITLE
[CONSULTA] ¿Cómo resizear correctamente el elemento?

### ISSUE THREAD

**Issue by afska** [Program-AR/gs-element-blockly#45]
Actualmente lo que está en http://gobstones.github.io/gobstones-web/#/blocks agarra el evento **resize** de `window` y le setea a `#blocklyDiv` el `width` y el `height` del panel. Eso como verán no anda muy bien (si cambiás el ancho, no se actualiza hasta que cambiás el alto).

Luego leí que hay una "forma correcta" de manejar esto según blockly: https://developers.google.com/blockly/guides/configure/web/resizable

Pero no sé si estará o no implementado en el componente. Si es así, ¿cómo lo uso?

**Comment by miguelgarcia** [comment]
Hola Rodri, proba con la versión 0.2.12, agregue código para manejar el evento:

https://github.com/Program-AR/gs-element-blockly/commit/e42ecab5897a113ea89f4b367dce2891e69d609d

**Comment by afska** [comment]
Anda joya! Hay un detalle que es que al iniciar se crea con un width y height predefinido (ver https://gobstones.github.io/gobstones-web/#/blocks) y hasta que no se resizea el panel no se adapta.

Una solución muy barata podría ser que yo le pase al elemento el width y height inicial deseado, o capaz se te ocurre una mejor solución @miguelgarcia para triggerear un resize al dibujar el elemento.

**Debug info:**
Si yo hago:
```js
setTimeout(() => {
  $(window).trigger("resize");
}, 500);
```
se soluciona, pero con esos 500 estoy inventando (con un poco menos ya no anda), tal vez ustedes tienen acceso al momento exacto en el que blockly termina de cargar y ya se puede hacer eso.

**Comment by miguelgarcia** [comment]
Agregue las propiedades width y height al elemento
