### ISSUE TITLE
Falta configurar el mensaje del bloque BOOM

### ISSUE THREAD

**Issue by afska** [Program-AR/gs-element-blockly#47]
La sintaxis sería:
```
program {
  BOOM("un mensaje de error")
}
```

(deben ser comillas dobles sí o sí)

**Comment by afska** [comment]
@faloi Esto es correcto no? Por lo que recuerdo de lo que hablamos el `BOOM` lleva mensaje, y no hay BOOM sin mensaje

**Comment by afska** [comment]
O tal vez @fidel-ml nos sepa decir

**Comment by asanzo** [comment]
Sí, sí, va con mensaje :)

**Comment by faloi** [comment]
Como está ahora rompe porque el mensaje sí es obligatorio. Hay que arreglarlo en el corto plazo.
