### ISSUE TITLE
El código de los procedimientos tiene comentarios adicionales

### ISSUE THREAD

**Issue by afska** [Program-AR/gs-element-blockly#48]
![screenshot at 2017-02-15 00-44-28](https://cloud.githubusercontent.com/assets/1631752/22959877/57651998-f342-11e6-93b4-1d1eda33161d.png)

Habría que sacar el comentario de arriba ("/** * Describe el procedimiento... */")

**Comment by asanzo** [comment]
No creo que @fidel-ml esté  de acuerdo en que haya que sacarlo.  Fijate que ese comment es el que aparece al apretar el signo de pregunta azul en la definición del procedimiento . Es la documentación del procedimiento, donde podes escribir pre y post condiciones.

Si quieren podemos charlar sobre ese default, también,  en el caso de dejarlo.

**Comment by afska** [comment]
Entiendo, no sabía que se podía configurar.

¿A alguno le molesta si por ahora cambio la sintaxis de los comentarios? Por alguna razón los comments con "/**" están rompiendo :stuck_out_tongue:

**Comment by miguelgarcia** [comment]
@rodri042 Ahora integro el cambio en los comentarios !
