### ISSUE TITLE
[CONSULTA] Procedimientos de biblioteca del alumno

### ISSUE THREAD

**Issue by afska** [Program-AR/gs-element-blockly#50]
@miguelgarcia @asanzo 

Para implementar la biblioteca del alumno, ya sea que lo haga con dos instancias de `<gs-element-blockly>` o con una (cambiándole el `workspaceXml` cada vez) me va a pasar que los dos workspaces me queden inconexos: Los procedimientos que el alumno escriba en la biblio no los va a poder ver en el principal ¡y no los va a poder usar! :(

¿Teníamos pensada una forma de hacer esto o se nos pasó totalmente?
¿Qué tal una propiedad `libraryProcedures` (que funcione al igual que `primitive Procedures` pero que los agregue en la categoría normal de **Procedimientos** como si los definiera en ese mismo workspace?

**Comment by asanzo** [comment]
Mmmm creo que idealmente deberían estar todos dentro de la categoría "Procedimientos". ¿No, @fidel-ml?

@miguelgarcia ¿Te animás a probar qué sucede si intentás agregar bloques a la categoría del toolbox que tiene `custom='PROCEDURES' ` ?

Creo recordar que el puto de blockly te la vaciaba, no te dejaba usarla para otra cosa que no fueran sus procedimientos. En ese caso, una solución de compromiso sería tener la categoría "Procedimientos de la biblioteca", como dice Rodri.

**Comment by fidel-ml** [comment]
El tema de la biblioteca del alumno está en discusión...
Por el momento, deberían ser bloques como cualquier otro procedimiento
definido por el estudiante.
O sea, técnicamente, la biblioteca hoy debe funcionar como parte del
espacio de trabajo común.
Quizás en algún tiempo definamos que en realidad las cosas ahí vayan a los
"Procedimientos primitivos", pero aún no está conversado.
FF

2017-02-15 12:54 GMT-03:00 asanzo <notifications@github.com>:

**Comment by afska** [comment]
Igual me parece piola que queden en una categoría aparte los de la biblioteca, no sé.

Se me ocurre esta interfaz:
- propiedad **libraryProcedures**: Array al estilo `["PonerBolitasEn(color,direccion)", "MoverMuchoHacia(color)"]`

- propiedad `libraryFunctions` similar a lo anterior pero para funciones.

- Al cambiar cualquiera de esas propiedades, si en el workspace se está usando un procedimiento o función que ya no está más (la borró de la biblioteca, le cambió parámetros de entrada o su nombre) => que se borren esos bloques.

**Comment by asanzo** [comment]
@rodri042 ¿Qué tanto les costaría meterlos en primitiveProcedures? Tendrían que transformar los nombres de procedimientos agregando guiones bajos al setear la propiedad, y volar los guiones bajos de esos procedimientos (pero no de otros) en la respuesta de generateCode() antes de ejecutar.

Me revienta la cantidad de categorías que tenemos, me gustaría disminuirla. Además, claro está, podemos gastar tiempo en otras cosas.

**Comment by afska** [comment]
Hmm. A ver, pienso en voz alta:

El pibe en la biblioteca define *PonerEn*, y dice que tiene dos argumentos:
color y dirección.

Al compilarlo me genera algo como:
procedure PonerEn(color, direccion) {
  // etc...
}

Yo parseo eso y al saber que existe ese procedimiento y tiene dos
argumentos, te paso como primitiveProcedures: ["PonerEn__"]

Blockly lo muestra y me lo deja usar pero cuando genero el código, las
llamadas figuran:
PonerEn__(Rojo, Norte)

Las cuales tengo que reemplazar sacándoles los guiones bajos.

Posible es, pero tal vez genere confusión al estar en "procedimientos
primitivos" ya que no son tan primitivos: los primitivos posta ejecutan de
una en el paso a paso, y los de la biblioteca del alumno no.

**Comment by asanzo** [comment]
Agree. ¿Y qué tal si ponemos tanto los procedimientos primitivos como los de la biblioteca en una categoría "Biblioteca de procedimientos" (y volamos "procedimientos primitivos"?

O sea, estoy proponiendo un cambio de nombre de categoría.

@fidel-ml?

**Comment by fidel-ml** [comment]
No son procedimientos primitivos. Esos procedimientos son una categoría que
usamos en el manual, y los procedimientos de biblioteca no están entre
esos...
Los procedimientos de biblioteca son procedimientos como cualquiera, y
podrían ir en la categoría de procedimientos definidos por el usuario. Si
los vamos a distinguir, podrían ser por color, pero no por categoría.
Si más adelante decidimos que van a procedimientos primitivos, hacemos lo
que decís, Alf.
FF

2017-03-01 20:21 GMT-03:00 asanzo <notifications@github.com>:

**Comment by fidel-ml** [comment]
Respondí la primera antes. Ahora respondo el resto.
Procedimientos primitivos es una categoría teórica que aparece en el
manual, y muchas actividades hacen uso de ellas. No las podemos volar así
no más...
Sobre los otros, como dije, por ahora son procedimientos comunes y
corrientes.
FF

2017-03-01 21:46 GMT-03:00 Fidel <fidel@unq.edu.ar>:

**Comment by asanzo** [comment]
Insisto en que hay demasiadas categorías, es confuso. 

Sin embargo, como hay que avanzar y resolver, hagámoslo [como propuso Rodri](https://github.com/Program-AR/gs-element-blockly/issues/50#issuecomment-280254981). 

Cierro este issue de discusión y abro uno para ya cargar la tarea.

**Comment by fidel-ml** [comment]
Alf, no me importa si son pocas o muchas. Lo importante es que sigan una
lógica conceptual. Y así las armamos.  Por eso dije que no hacen falta
distinguir las funciones de la biblioteca: no es una categoría conceptual
diferente. Por lo tanto, la sugerencia de Rodri no hace falta implementarla.
Pero si mis requerimientos. ;)
FF

2017-04-06 19:07 GMT-03:00 asanzo <notifications@github.com>:

**Comment by asanzo** [comment]
Buenas! Hoy no se puede agregar nada a la categoría Procedimientos, porque es una categoría que maneja Blockly como se le canta.

Entonces, tenemos los bloques de la biblioteca, que no podemos agregar a Procedimientos porque Blockly no te deja, y no podemos agregar a Procedimientos Primitivos porque habría problemas de implementación y además conceptuales, por lo que terminan en otra categoría.

Podemos implementar nuestra propia categoría "Procedimientos", pero es costoso y desplazaría otros issues importantes. Si quieren, lo ponemos a discusión. No por este medio.
