### ISSUE TITLE
"Cannot read property 'isConnected' of null" al cargar un xml

### ISSUE THREAD

**Issue by afska** [Program-AR/gs-element-blockly#52]
Nos tira ese error cargando este xml:

```xml
<xml xmlns="http://www.w3.org/1999/xhtml"><block type="Program" id="{XiKDv/%.3{(~rx0EF~*" deletable="false" movable="false" editable="false" x="30" y="30"><statement name="program"><block type="procedures_callnoreturn" id="VX~YA}X|YG.ej0U5*)s+"><mutation name="Repartir caramelos"></mutation><next><block type="procedures_callnoreturn" id=":6V{C^`ucRTL%VLn[]L^"><mutation name="Recolectar papeles"></mutation></block></next></block></statement></block><block type="procedures_defnoreturn" id="7uQ8[(hgK$*j-$(gs0nG" x="29" y="157"><field name="NAME">Repartir caramelos</field><comment pinned="false" h="80" w="160">Describe el procedimiento...</comment><statement name="STACK"><block type="Repetir" id="FG|pBJ4r-~yJ`m_,rJQp"><value name="count"><block type="math_number" id="WL(,(B~+*[e*,zl76Gms"><field name="NUM">19</field></block></value><statement name="block"><block type="IrAlProximoEstudiante" id="w+[}Z~X+/OPx-smKg$K["><next><block type="DarCaramelo" id="@M`SO=EC!*PQntKvTK(Y"></block></next></block></statement><next><block type="IrAlEscritorio" id="v}#i$d=$=S|NNp8?8b(1"><next><block type="ComerCaramelos" id="~$R#ZL0*p3+D(y2U$u~I"></block></next></block></next></block></statement></block><block type="procedures_defnoreturn" id="l!UoPXA~5R%umTChNj5d" x="294" y="155"><field name="NAME">Recolectar papeles</field><comment pinned="false" h="80" w="160">Describe el procedimiento...</comment><statement name="STACK"><block type="Repetir" id="%b)*!nUW/o8Cja|{KCh:"><value name="count"><block type="math_number" id="^;8gt/7ifqTNu;6..aty"><field name="NUM">19</field></block></value><statement name="block"><block type="IrAlProximoEstudiante" id="aY3qgGQ+c3_4W#Tex(jj"><next><block type="RecolectarPapel" id="Lx??!jmx8|Xyp1OFg$)k"></block></next></block></statement><next><block type="IrAlEscritorio" id=";Ne$)I+hI[SK`N:H1?,F"></block></next></block></statement></block></xml>
```

Para reproducirlo se puede desde https://gobstones.github.io/gobstones-web/#/blocks ir al menú -> cargar bloques y elegir ese xml guardado como `algo.gbjs`

EDIT: Anda en los intentos pares: la segunda vez sí, la tercera no, la cuarta sí, etc

**Comment by asanzo** [comment]
Buenas!

Pregunta: ¿Están esos procedimientos primitivos definidos en el toolbox en el momento de intentar cargar ese xml?

Me refiero a `IrAlProximoEstudiante`,  `DarCaramelo`, `IrAlEscritorio`, `ComerCaramelos`, `RecolectarPapel`.

Acabo de [agregar un test](https://github.com/Program-AR/gs-element-blockly/commit/d9070ea06beca1c0ce71e3a2ce277a6861e165fc) que prueba que esto anda joya, si agregás los primitive procedures antes de pisar workspaceXML:

![seleccion_144](https://cloud.githubusercontent.com/assets/5421992/24153975/aa5cc3ba-0e2e-11e7-9cc6-2d629ed79316.png)

**Comment by afska** [comment]
Tiene mucho sentido XD. Haciendo eso empezó a andar, y solo falla la primera vez (mismo error), no sé todavía por qué. Voy a jugar un poco más y si no lo logro vuelvo

**Comment by afska** [comment]
Ya entendí mejor. Efectivamente esto se da cuando el código a setear usa los `primitiveProcedures`. 

Pasa algo así:
- Asigno los `primitiveProcedures`
- Seteo el código. Blockly todavía no *hizo su magia* entonces esto falla.
- Blockly *hace su magia*, redibuja y qué se yo, y aparecen los procedimientos primitivos que asigné.
- Si reintento cargar el proyecto, ya anda porque ya están los procedimientos primitivos cargados.

Entonces me da a pensar que la asignación de los primitive procedures no es tan sincrónica como me gustaría y hay que esperar a que blockly termine para después poder setear el código, el tema es que yo no sé cuándo eso ocurre, obvio que con un `setTimeout(..., 100)` funciona, pero estaría piola tener alguna forma de saber cuándo puedo setearlo, o mejor aún, que el elemento se de cuenta de esto y "banque" el pedido hasta que se pueda realizar.

**Comment by asanzo** [comment]
@rodri042 No lo puedo reproducir.

En el [test que agregué](https://github.com/Program-AR/gs-element-blockly/commit/d9070ea06beca1c0ce71e3a2ce277a6861e165fc) hago exactamente lo que vos decís:

```javascript
// asigno los primitive procedures
+  element.primitiveProcedures = [ "IrAlProximoEstudiante", "DarCaramelo", "IrAlEscritorio", "ComerCaramelos", "RecolectarPapel"];
// Seteo el código
+  element.workspaceXml = '<xml xmlns="http:/..........';
```

Y el test corre bien de una.

Incluso me hice un botón que haga esas dos cosas automáticamente (para probar directamente en la app y no en el test), y me dibuja genial los bloques.  (Puedo hacer tu paso 1 y paso 2 sin fallas). [Acá el branch donde lo probé](https://github.com/Program-AR/gs-element-blockly/tree/pruebaRodriPrimitiveProcedures).

¿Me darías una url para probarlo?

**Comment by afska** [comment]
@asanzo perdón el super cuelgue. Lo estuve debuggeando más y era un problema de gobstones-web. Ya lo arreglé!
