### ISSUE TITLE
Generar automáticamente una lista actualizada de los IDs válidos

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#54]
Para el docente que crea una actividad en Gobstones Web, es importante contar con la lista de categorías y bloques válidos, que son los que debe poner en la categoría `toolbox`.

Yo agregaría un método público `getValidIDs()` que retorne los IDs válidos, podría retornarlos en un json, lo cual podría servir también para que utilice GobstonesWeb:

```
// Output de getValidIDs():
// Diseño propuesto: objeto json con 2 propiedades: "category" y "contents". 
// Los contents pueden ser lista de objetos, ó bien lista de ids de bloques.

[
  { 
    category: "Comandos",
    contents: [
          { 
            category: "Comandos Primitivos",
            contents: ["Poner","Mover","Sacar","IrAlBorde","VaciarTablero","BOOM"] 
          },
          { 
            category: "Procedimientos"
          },
          { 
            category: "Alternativas",
            contents: ["SiEntonces","SiEntoncesSino"] 
          },
         // Etcétera.....
    ]
 { 
    category: "Expresiones",
    contents: [
          { 
            category: "Expresiones Primitivas",
            contents: ["hayBolitas","nroBolitas","puedeMover"] 
          },
     // Etcétera
```

Adicionalmente, haría que en el demo, abajo de todo, se imprima automáticamente esta lista (bonita, sin tanto json), para ofrecer un lugar de consulta centralizado para el docente.

**Comment by fidel-ml** [comment]
Por ahora para el docente, no sé. Pero a mí me vendría bien.
Por prueba y error comprobé que el ID "Operadores" no funciona, y sí funciona "Operaciones". Habría que cambiarlo (con tiempo ;)).

**Comment by asanzo** [comment]
Fidel, @rodri042, versión 0.3.0
