### ISSUE TITLE
Sanitizar la entrada de BOOM

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#57]
Tests que hizo Fidel (estaría bueno que en todos los casos andara, ó diera un error decente):

a.- <<Hacer BOOM porque:Ingresar motivo...>> sin cambiar, da "Unknown operator"
b.- <<Hacer BOOM porque:.>> con un punto, da "Unknown operator"
c.- <<Hacer BOOM porque:..>> con dos puntos, anda bien.
d.- <<Hacer BOOM porque:">> con una comilla, da "Se esperaba ")" pero se encontró """."
e.- <<Hacer BOOM porque: >> con un espacio, anda bien.
f.- <<Hacer BOOM porque:>> borrando todo, todo, NO HACE NADA! (Ni BOOM, ni error, ni nada... :().

**Comment by asanzo** [comment]
@rodri042 @faloi 
Por ahora estamos dejando escribir lo que sea, y clavándole una comilla adelante y una atrás.
¿Qué forma debería tener lo que les llegue?

**Comment by afska** [comment]
Ahí probé con **gobstones-web** y la demo de **gs-element-blockly**.

**a** y **b** son lo mismo: hay un tema cuando el string contiene puntos.
**f** re turbio, es también de GW.

Lo único a solucionar de parte de ustedes para mí es el **d**, donde cosas como `Hola"Mundo` deberían generarse como `Hola\"Mundo`. Esto no significa que eso vaya a funcionar, pero es un primer paso. El tema es que el compilador de GW no tiene el concepto de strings y todavía hay que meterle bastante mano a ese `BOOM(...)`. Peeero, para que ya vaya quedando bien, sería bueno que las comillas se escapen con `\"` o algo así.

**Comment by asanzo** [comment]
Listo, ahora estoy sacando las _primeras_ comillas envolventes, si es que existen, y además escapando todas las otras que aparecen con contrabarra.

Ahora escribir `Li"ndo` en el bloque va a escupir `BOOM("Li\"ndo")`.
Ahora escribir `"Li"ndo"` en el bloque va a escupir  `BOOM("Li\"ndo")`.
Ahora escribir `""Li"ndo""` en el bloque va a escupir `BOOM("\"Li\"ndo\"")`.

Ya está disponible en la versión 0.2.7

Cierro el issue y cualquier cosa se reabre si es necesaria otra cosa de este lado.

**Comment by afska** [comment]
@asanzo Hice un PR sobre esto en https://github.com/Program-AR/gs-element-blockly/pull/64
