### ISSUE TITLE
Configuración Inicial del toolbox configurable por parámetro

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#6]
En Gobstones Web va a haber idea de "Actividades", donde **se espera que los editores que se muestren sean ligeramente distintos**.

En principio, entre las distintas actividades los editores sólo diferirían en que _algunas categorías se mostrarán y otras no_, y _algunos bloques se mostrarán y otros no_.

Entonces, el componente gs-element-blockly **debería recibir por parámetro las categorías y/o bloques a mostrarse**.

Me gustaría definir con el equipo de Gobstones Web qué interfaz esperarían que tenga el componente para lograr esto.

¿Qué queremos? ¿Que existan parámetros como "showCategories=['alternativas','repeticiones']" y/o "hideCategories" y "showBlocks" y "hideBlocks"? ¿Ú otra cosa de más alto nivel?

@faloi , ¿opiniones?

**Comment by faloi** [comment]
Lo que queremos con @fidel-ml son dos niveles de configuración: bloques visibles y bloques activados. 

Esto no es capricho sino que responde al siguiente principio: toda herramienta que fue presentada en una actividad tiene que quedar visible en todas las siguientes, de modo que la caja de herramientas **siempre** se incremente. Aún así, en algunas actividades puede tener sentido no permitir el uso de ciertos bloques.

En cuanto a la granularidad, deberíamos poder hacer esta configuración a nivel bloque: oculto, visible habilitado, visible deshabilitado. Las categorías deberían aparecer solamente cuando alguno de sus bloques aparecen.

**Comment by asanzo** [comment]
Buenas!

Según esto, distingo tres estados posibles:

- Visible y habilitado: Aparece en el toolbox y se puede usar normalmente.
- Visible y no habilitado: ¿Aparecería en el toolbox grisado y sin poderse usar?
- No visible: No aparece en el toolbox, independientemente de estar habilitado ó no. 
- Descarto que esté no visible y habilitado, porque **no se puede usar un bloque que no esté en el toolbox**. Esto es un feature raro que nacía de poder importar soluciones en Pilas Bloques, cosa que en Gobstones Web, según entiendo, no va a pasar.

En general, tengo problemas con el "habilitado". No veo la necesidad pedagógica. Si no querés que el pibe use un bloque, no lo pongas en el toolbox y listo. ¿Qué ganás con mostrárselo grisado? Es de mala persona eso :stuck_out_tongue_closed_eyes: 

Quizás cuando hablamos de codificación escrita tiene más sentido hacer esa división.

--------------------------------------

Más allá de eso, (se haga ó no se haga lo de habiliado), entiendo que la responsabilidad de decidir qué bloques nuevos se agregan en una actividad está del lado de la app Gobstones Web, y no del componente gs-element-blockly.

Entonces, pregunto:

¿Bastaría con implementar properties así?

```html
<gs-element-blockly visibleBlocks:'[Rojo, Verde, Azul, Repetir, RepetirHasta, Sacar, Poner]'></gs-element-blockly>
```

**Comment by faloi** [comment]
Fue una discusión larga que tuvimos en el equipo, le dejo a @fidel-ml la tarea de reproducirla.

La interfase (nunca sé cómo escribir esa palabra) me parece que está bien, aunque no termino de ver por qué tiene que ser HTML. Algo que me imagino que sería interesante es tener una forma de consultar qué bloques existen y en qué categorías están, para eventualmente armar una UI que te deje seleccionar.

@rodri042, porfa opiná sobre lo que propone Alf.

**Comment by afska** [comment]
Sí. Para mí estaría bien así. Aunque si hacemos lo de bloques grisados deberían ser dos grupos (visibles y deshabilitados). 

Sería copado que eso se pueda bindear contra una propiedad y se puedan agregar bloques visibles sin tener que recargar el elemento, perdiendo así lo que fue armando el pibe. Pero ojo, estoy volando, todavía no hablamos nada de cómo encarar las actividades

**Comment by fidel-ml** [comment]
La idea pedagógica es que vos le estás enseñando una serie de herramientas
conceptuales, y armando un mapa mental con las mismas.
Entonces, si ya conoce una herramienta, tiene que aparecer en el mapa: no
tiene sentido un mapa que cambia a cada rato, pero sí uno que crece
(sacando "FoW"... :)).
Sin embargo, hay actividades que invitan a solucionar el problema de cierta
manera, y entonces se requiere que no utilicen algunas de las herramientas
(por ejemplo, si quiero forzar a que use while, le pido ir al borde, pero
sin usar la primitiva... :)). Incluso, pensando más allá (de manera
inconsulta), se me ocurre que si hay procedimientos dados como "primitivos"
(no son primitivos pues son procedimientos, pero vienen hechos en la
actividad), puedo querer que usen esos y no los comandos primitivos posta
(por ejemplo, tengo PonerManzana() y SacarManzana() y no quiero que usen
Poner(?) o Sacar(?), ¿se entiende?)

2016-12-01 17:48 GMT-03:00 asanzo <notifications@github.com>:

**Comment by fidel-ml** [comment]
La disposición en grupos de los elementos es fija, estén o no
deshabilitados. O sea, el mapa tiene que ser EL MISMO a lo largo de todas
las actividades, y solo se puede incrementar a medida que cada actividad es
más avanzada.
No sirve que se agrupen los deshabilitados en un lado separado...

Si trata de usar un comando deshabilitado, el mensaje debería ser algo como
"Esta actividad tenés que solucionarla sin este elemento" o algo así.


El mapa se parecerá mucho al que vimos con Alf para PilasBloques (¿lo tenés
para compartir, Alf, así no lo recreo?), con el agregado de que va a haber
"procedimientos primitivos" además de "comandos primitivos" (los comandos
primitivos son Poner, Sacar, Mover, IrAlBorde, VaciarTablero, mientras que
los procedimientos primitivos son aquellos definidos en la biblioteca del
docente, que son atómicos).



2016-12-01 18:44 GMT-03:00 Rodrigo Alfonso <notifications@github.com>:

**Comment by asanzo** [comment]
El mapa del que habla Fidel está [acá](https://github.com/Program-AR/gs-element-blockly/issues/1).

Que aparezca siempre en la misma categoría ya lo habíamos implementado en Pilas Bloques, es factible. Lo detallo en #9

Desde la aplicación Gobstones Web (no desde este componente) se va a decidir qué bloques se muestran y qué bloques no, idem con estar habilitados ó no. La lista de bloques la tienen que armar ellos, por ahora. Quizás les agreguemos, como dice Fede, una forma de obtener la lista de bloques.

Sobre "Procedimientos primitivos", eso es un feature diferente. Avancemos sobre el feature presente y después vayamos a ese. Hay cosas a discutir por separado.

Respecto de estar "habilitado", cito a @fidel-ml :
> Si trata de usar un comando deshabilitado, el mensaje debería ser algo como "Esta actividad tenés que solucionarla sin este elemento" o algo así.

¡Momento!

Yo me imaginaba que cuando un bloque estaba deshabilitado entonces se listaba grisado **Y** no se podía mover del toolbox.

¿Vos querés que se pueda usar ese bloque deshabilitado?

P.D.: Fidel, ¡por el amor de Gauss dejá de hacer tus propios saltos de línea! :laughing: Me pone frenético.  :sweat_smile:

**Comment by fidel-ml** [comment]
No, no quiero que se pueda sacar del toolbox. Pero si se para arriba y
trata de sacarlo, estaría bueno un mensaje de error que le diga por qué no
puede. Si es quilombo, y el gris es como que no existe, entonces leesto.


PD: Qué es "mis propios saltos de línea"?

2016-12-02 18:56 GMT-03:00 asanzo <notifications@github.com>:

**Comment by asanzo** [comment]
@miguelgarcia 

Hoy hay un problema. La interfaz que figura es la siguiente:

![seleccion_057](https://cloud.githubusercontent.com/assets/5421992/22481244/43ea3134-e7d3-11e6-9ff9-0ae547d6cc07.png)

Pero en el issue #23 Figura "Entra: lista de ids de bloques visibles, y lista de ids de bloques deshabilitados."

¿Por qué es un String? Deberían ser **dos listas**.

Hablando con la gente de Gobstones, dijimos que un ejemplo posible es _de tipo object ó JSON_, con dos key/value:

```json
{
"visible": ["Comandos primitivos", "Literales", "Expresiones"],
"disabled": ["Poner", "hayBolitas", "Literales"]
}
```

Notar ahí un feature adicional: puede venir un nombre de categoría, para no tener que escribir todos los bloques de esa categoría. Podemos charlar esto último, pero el object con las dos listas debe estar.
