### ISSUE TITLE
Usabilidad funciones y procedimientos

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#60]
Ideas que tiró Fidel:

- Los parámetros deberían poderse "obtener" para usarse fácilmente (no click derecho...) ¿quizás como scratch?
- Los parámetros y variables de un procedimiento no deberían poderse usar fuera de él...
- Debería poderse crear un procedimiento por el usuario que tenga texto + parámetro + texto + parámetro, y así...

**Comment by fidel-ml** [comment]
Algunas de estas ya están... Y otras están duplicadas. ¿Vale depurar este issue? ¿Alf?

**Comment by asanzo** [comment]
Hechos:

- Las Funciones y los procedimientos deben poder estar en categorías separadas
- La definición de la función/procedimiento debería estar diferenciada del bloque de llamada a función/procedimiento. ¿Quizás con un botón "nuevo procedimiento", como en code.org?

Ya hay issue para:
- #81 Deberían poderse crear funciones puras (sólo return, sin sentencias)
- #24  El procedimiento podría ser "colapsable", de la misma forma que en un IDE se puede colapsar un bloque "if", por ejemplo, para que no se vea el código.

Faltan:
- Los parámetros deberían poderse "obtener" para usarse fácilmente (no click derecho...) ¿quizás como scratch?
- Los parámetros y variables de un procedimiento no deberían poderse usar fuera de él...
- Debería poderse crear un procedimiento por el usuario que tenga texto + parámetro + texto + parámetro, y así...

Modifiqué el issue para dejar estos. No lo separo en tres porque creo que no es sabio encarar estas tres cosas ahora, y me parece que habría que encararlas como una nueva interfaz de creación de procedimientos. No estoy muy convencido de seguir parchando los procedimientos.

**Comment by afska** [comment]
Este issue quedó medio viejo, lo cierro!
