### ISSUE TITLE
Que se grise el bloque no conectado, como en pilas bloques

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#62]
@fidel-ml @faloi

![seleccion_177](https://cloud.githubusercontent.com/assets/5421992/25146030/e7389bbc-2448-11e7-8de7-aa779e6fd857.png)

¿Qué codigo les gustaría que escupa un bloque grisado?

¿Evito generar código ó genero de todas formas, como sucede ahora?

Imagino que tiene que ver con la forma en la que quieran mostrar los errores.

**Comment by faloi** [comment]
Para mí un bloque no conectado no existe, y no quiero que genere nada. 

El caso de uso que me imagino para esto es _"estoy probando qué hacen estos comandos y mientras tanto dejo estos otros acá al lado"_, lo cual vi infinitas veces en la forma de laburar de los pibxs de secundaria.

**Comment by fidel-ml** [comment]
Con ese criterio, entonces, debería aparecer grisado, y no generar código...
FF

2017-04-18 15:09 GMT-03:00 Federico Aloi <notifications@github.com>:

**Comment by faloi** [comment]
Sí. No sé si me parece super necesario que esté grisado, pero sin dudas ayuda visualmente a comprender que no va a ejecutarse (¿quizás bajarle la opacidad en vez de volverlo gris, para no perder el código de colores?).

**Comment by fidel-ml** [comment]
Según lo que decía FedeA, un bloque grisado no genera código.
FF

2017-04-18 15:02 GMT-03:00 asanzo <notifications@github.com>:
