### ISSUE TITLE
Instalar componente como dependencia de bower

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#7]
Copio del mail original de @rodri042 

Necesitaríamos que el `<gs-element-blockly>` se pueda instalar como componente bower. Creo que en ese repo hay una task de gulp que prepara todo y sube a una branch el artifact para que cuando uno instale el paquete solo se baje lo necesario.

Un primer paso podría ser hacer algo como:

```
bower install Program-AR/gs-element-blockly#dev
```

```html
<html>
  <head>
    <link rel="import" href="bower_components/gs-element-starter/app/gs-element-blockly.html">
  </head>
  <body>
    <gs-element-blockly></gs-element-blockly>
  </body>
</html>
```

... y que eso muestre el elemento. Ahora no está andando y habría que ver bien por qué. Me parece que son solamente referencias a bower_components que quedaron mal. Cualquier cosa armamos una call y lo vemos juntos!

**Comment by asanzo** [comment]
@rodri042 Esto ya está hecho, ya pueden hacer:

```
bower install gs-element-blockly
```

Nosotros tenemos varias cosas para avanzar, pero estaría bueno empezar a intentar integrar y descubrir problemas que surjan.

**Comment by afska** [comment]
Hola!

Estuve probándolo y no lo pude hacer andar, ¿alguno me da una mano?
Dejo la prueba que hice: https://github.com/rodri042/prueba-blockly

Algunas cosas:
- https://github.com/Program-AR/gs-element-blockly/blob/518b7930c0681b85d9eb1f04520884bf63eaddd6/app/gs-element-blockly.html#L34 este `<h1>` indicando el nombre del componente deberíamos sacarlo, así al incluir el elemento queda solo el workspace de Blockly.
- https://github.com/Program-AR/gs-element-blockly/blob/518b7930c0681b85d9eb1f04520884bf63eaddd6/app/gs-element-blockly.html#L11 acá entiendo que no deberíamos importar Polymer, ya que de eso se encarga la aplicación contenedora (ya sea la demo del componente o Gobstones Web).
- https://github.com/Program-AR/gs-element-blockly/blob/518b7930c0681b85d9eb1f04520884bf63eaddd6/app/gs-element-blockly.html#L272 y acá parece estar el problema. Escribiendo `../../blockly-package/etcétera` va a andar pero si solo hacemos eso se rompería el demo con el que desarrollan. La solución parece estar en seguir las recomendaciones de este link: https://divshot.com/blog/web-components/polymer-and-bower-getting-it-right/ (lo que dice del `.bowerrc`).

Entonces, siempre deberíamos pensar que nuestras dependencias externas (en este caso `blockly-package`) van a estar un directorio atrás de donde se encuentre el `bower.json`.

**Comment by afska** [comment]
Comprobado. Cambiando esos items se solucionaría el tema:

![screenshot2](https://cloud.githubusercontent.com/assets/1631752/21796160/7b2fcc64-d70f-11e6-872a-4de5e546e9d0.png)

**Comment by asanzo** [comment]
Bueno, estoy intentando avanzar algo antes de que llegue Mike. 

Ya pude reproducir todo lo que menciona @rodri042. Incluso ya hice los cambios en el branch https://github.com/Program-AR/gs-element-blockly/tree/bowerParalelo , y lancé una versión de prueba 0.0.4 a bower (ya anda el proyecto de prueba de rodri, si actualizás la versión de gs-element-blockly en su bower.json)

**pero todavía no mergeé a master**.

Primero, quiero entender:

> siempre deberíamos pensar que nuestras dependencias externas (en este caso `blockly-package`) van a estar un directorio atrás de donde se encuentre el `bower.json`.

¿Cambiamos entonces el default de [gs-element-starter](https://github.com/gobstones/gs-element-starter) ?

Porque al iniciar el componente nos habíamos atenido a ese template, y ahí el `.bower_rc` dice `"directory": "client/bower_components"`.

Todavía tengo que gastarle tiempo al gulpfile para que el "gulp" a secas y el "gulp test" anden.

**Comment by afska** [comment]
> ¿Cambiamos entonces el default de gs-element-starter ?

Si esos cambios que tenés sin mergear funcionan, por mí sí. Ese `gs-element-starter` está medio abandonado, más que nada porque ningún componente **actual** de gobstones web lo está usando. El tablero es el único componente externo pero es más viejo y no está basado en él.

**Comment by asanzo** [comment]
Entonces para mí hay que repensar la estructura y hacerlo bien de una. 

Mientras tanto, la versión 0.0.4 ya anda.

¿Tenés alguna recomendación de estructura para el componente, @rodri042 ?

Tenemos poca experiencia en Polymer y me gustaría limpiar ahora que se puede, temprano, esto.  La estructura de ahora es innecesariamente compleja.

**Comment by afska** [comment]
Concuerdo. Hmm, en la docu oficial de Polymer recomiendan https://github.com/PolymerElements/polymer-starter-kit

**Comment by asanzo** [comment]
¿ Eso no es para hacer una app completa?

Ahí estuve chusmeando la doc de Polymer. Esta guía para un [reusable element](https://www.polymer-project.org/1.0/docs/tools/reusable-elements) parece que es la que hay que usar. De ahí más o menos creo que sabemos todo, sólo hay que darle bola a la última parte que dice una forma fácil de publicar una demo.

Dentro de ese lugar linkean a [Element Project Layout](https://www.polymer-project.org/1.0/docs/tools/polymer-cli#element), que es la estructura que estamos buscando.

¿Es más apropiado ese?

**Comment by asanzo** [comment]
Bueno, no pude conmigo, así que ya limpié todo. Perdón si volé cosas de más, pero me pareció que mientras más limpio mejor.

@miguelgarcia ya no usamos gulp-cli, ahora usamos polymer-cli. Te recomiendo reclonarte el repo. Los pasos para la construcción están en el README. Eliminé las branches innecesarias, creé un pre-release 0.1.0 que anda bien con bower.

@rodri042 te hice un PR para tu proyecto de prueba. Ahora que terminamos con esto podemos seguir con el issue importante, el #25 . 

Ah, yapa para fidel: Ahora también cualquiera puede probar el element en https://program-ar.github.io/gs-element-blockly . Cuando arreglemos el issue 25 vamos a poder meter todo en travis, porque los tests van a poder correr. Por ahora el update de eso se hace siguiendo las instrucciones en https://www.polymer-project.org/1.0/docs/tools/reusable-elements#publishing-a-demo-and-landing-page-for-your-element
