### ISSUE TITLE
Soportar apóstrofes en nombres de procedimientos / funciones primitivas para indicar mayúsculas

### ISSUE THREAD

**Issue by afska** [Program-AR/gs-element-blockly#72]
Detalle en https://github.com/gobstones/gobstones-web/issues/190

**Comment by fidel-ml** [comment]
No es suficiente. Si hoy uso comas u otros símbolos en el nombre de un procedimiento, el código generado hace cosas raras...
![bugEnBloques.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bad8a160fd7e2000a7c8c6/125516c66e82c728ace21e0d46ea819d068ca1a580f8aa46b71fbcd6395428792c07b7692ac7b670b9142e585f0e48aa46500d42fcf98b2df4e03478d95919f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bc8f45c0ee3822e2828c4b2c53.png)

**Comment by fidel-ml** [comment]
Es necesario tener un mecanismo de interfaceo entre nombres de bloques y nombres de texto que sea flexible... Por ejemplo, usar pragmas. En el programa del ejemplo, se podría generar

//@BlockName: "Nueva prueba de coma, beatch"
procedure NuevaPruebaDeComaBeatch() {
  Mover(Este)
  Poner(Rojo)
}

program {
     NuevaPruebaDeComaBeatch()
 }

Marqué eso en gobstones/gobstones-web#190 y agregué gobstones/gobstones-web#201 para la sintaxis de esos pragmas...

**Comment by asanzo** [comment]
Duplicado/incluido en #87
