### ISSUE TITLE
Output con información de los bloques (pragma IDBlock)

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#77]
Para que luego sea posible que el intérprete provea mejor informe de errores (señalando el bloque problemático, por ejemplo) y también para que sea capaz de hacer una eventual iluminación del bloque en ejecución.

Para lograrlo podríamos comenzar por los comandos, agregando un pragma, por ejemplo algo así:

```Gobstones
///@blockId=af34
program {
    ///@blockId=2ty5
    PonerN(Rojo,3)
    ///@blockId=jh9k
    PonerN(Verde,5)
}

///@blockId=34tt
procedure PonerN(color,cant){
    ///@blockId=6ryy
    repeat(cant){
        ///@blockId=54yi
        Poner(color)
    }
}
```

Más adelante podemos pensar qué sucede en el caso de las expresiones, que tiene su complejidad.

------------------------------
EDIT:

Ejemplo actualizado:
```
/@BEGIN_REGION@af34@/
program {
    //@BEGIN_REGION@2ty5@/
    PonerN(Rojo,3)
    /@END_REGION@/
    /@BEGIN_REGION@jh9k@/
    PonerN(Verde,5)
    /@END_REGION@/
}
/@END_REGION@/

/@BEGIN_REGION@34tt@/
procedure PonerN(color,cant){
    /@BEGIN_REGION@6ryy@/
    repeat(cant){
        /@BEGIN_REGION@54yi@/
        Poner(color)
        /@END_REGION@/
    }
    /@END_REGION@/
}
/@END_REGION@/
```

:warning: Esto tendría que ser opcional a la hora de generar código (`generateCode({ withRegions: true })` o `generateCode()`) para que la opción "ver código generado" de gobstones-web siga mostrando código legible!

**Comment by fidel-ml** [comment]
¿Esa sintaxis de pragmas la inventaste o la sacaste de lo que hizo Pablo Barenbaum en el nuevo intérprete?

**Comment by asanzo** [comment]
Creo que la ví escrita en algún lado y la copié.

**Comment by fidel-ml** [comment]
La sintaxis de Pablo es
/*@NombreDePragma@Parametro-1@Parametro-2@...@Parametro-N@*/

Ejemplo:
/*@Blockld@6ryy@*/

Habría que agregar BlockId como nombre de pragma, pero es fácil.
El tema es si no habría que usar regiones... (o sea, cerrar cada bloque)

**Comment by afska** [comment]
Claro, para mí habría que usar regiones, ya que el intérprete nuevo me va a decir en qué región sucedió cada snapshot en el paso a paso y sería mucho más fácil.

@foones, ¿nos ayudás con esto? ¿cómo sería la sintaxis?

**Comment by foones** [comment]
La idea es delimitar las regiones usando esta sintaxis:

`/@BEGIN_REGION@6ryy@/`
`...`
`/@END_REGION@/`

- El motivo para tener un BEGIN y un END es para permitir que las regiones se puedan anidar.

- El motivo para forzar a que el usuario tenga que poner un END manualmente, en lugar de que el intérprete decida dónde va el end de acuerdo con la estructura sintáctica del programa, es que los pragmas se identifican a nivel léxico, es decir, en el momento de la tokenización previa al análisis sintáctico. Esto me parece medio inevitable, porque las regiones deberían funcionar aun si el programa está sintácticamente mal formado.

**Comment by afska** [comment]
Ahí actualicé la descripción del issue con el nuevo formato.

:warning: Esto tendría que ser opcional a la hora de generar código (`generateCode({ withRegions: true })` o `generateCode()`) para que la opción "ver código generado" de gobstones-web siga mostrando código legible!

**Comment by asanzo** [comment]
¿Por qué el objetito con las opciones? ¿Tenés alguna más en la cabeza que se me esté escapando @rodri42 ?

**Comment by afska** [comment]
Ah, solo por si en el futuro queremos agregar más sin romper la interfaz.
Pero tmb podría ser el booleano nomás

**Comment by asanzo** [comment]
Estoy mirando con cariño esto y veo que estamos olvidando las expresiones.

El procedure:

```Gobstones
procedure PonerN(color,cant){
    repeat(cant){
        Poner(color)
    }
}
```

Para `cant` escupiría también `/@BEGIN_REGION@43asdf@/cant/@END_REGION@/`y para `color`, ídem para los literales y todos los operadores y sensores, quedando:

```Gobstones
/@BEGIN_REGION@af34@/
program {
    /@BEGIN_REGION@2ty5@/
    PonerN(/@BEGIN_REGION@6754ytrew@/Rojo/@END_REGION@/,/@BEGIN_REGION@e4rtdsc@/3/@END_REGION@/)
    /@END_REGION@/
    /@BEGIN_REGION@jh9k@/
    PonerN(/@BEGIN_REGION@2w343dfasf@/Verde/@END_REGION@/,/@BEGIN_REGION@234fsdf@/5/@END_REGION@/)
    /@END_REGION@/
}
/@END_REGION@/

/@BEGIN_REGION@34tt@/
procedure PonerN(color,cant){
    /@BEGIN_REGION@6ryy@/
    repeat(/@BEGIN_REGION@43asdf@/cant/@END_REGION@/){
        /@BEGIN_REGION@54yi@/
        Poner(/@BEGIN_REGION@43asdf@/cant/@END_REGION@/)
        /@END_REGION@/
    }
    /@END_REGION@/
}
/@END_REGION@/
```

Y me acabo de dar cuenta que vamos a tener un problema porque los ID de Blockly pueden tener `@`.  @foones ¿Podemos envolverlos en comillas simples ó dobles, que uds después saquen? 

Esto es todo lo que puede tener un ID de bloque:

```
!#$%()*+,-./:;=?@[]^_`{|}~ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
```

Comenzando a analizar el requerimiento me encuentro con que el refactor que necesito clavar no es trivial, y necesito testear muy bien. Me va a llevar tiempo hacerlo.

**Comment by asanzo** [comment]
Hice un avance importante en https://github.com/Program-AR/gs-element-blockly/commit/d630b2c9e1dcf3645da73aabb9101702712a15bb (por ahora en el branch pragmaRegion )

![seleccion_070](https://user-images.githubusercontent.com/5421992/34395433-ee065700-eb3e-11e7-9b61-2fa6f9ee1608.png)

Puede probarse en https://program-ar.github.io/gs-element-blockly/

**Comment by afska** [comment]
Buenísimo!

Qué le falta? Lo podría ya integrar a gobstones-web?

**Comment by asanzo** [comment]
En el branch pragmaRegion lo tengo casi cocinado, tengo que terminar de hacer algunos tests.

Lo más importante seguro va a ser que @foones revise las decisiones que tomé sobre cómo escupir las regions de los diferentes bloques (programa interactivo, definiciones, bindings, expresiones, literales, etc.).

Entre hoy y mañana lo liquido, y éste es mi último aporte por un tiempo largo / indefinido (salvo algún parche rápido necesario)

**Comment by asanzo** [comment]
Bueno, muchachos, @fidel-ml @foones @rodri042 , terminé con esto.

- Pueden probarlo en https://program-ar.github.io/gs-element-blockly/
- Está en la versión ya subida [0.6.0](https://github.com/Program-AR/gs-element-blockly/commit/99bae654fb083f905c393bc19a325a1a7777916c) (Rodri, lo podés integrar)
- Cualquier cosa me chiflan. Como les dije, yo me voy a borrar por un tiempo largo, al menos oficialmente, porque desde la Fundación no puedo dedicarle mucho más tiempo.

Estos son los tests con los que lo probé:

|Limpio|Con Pragma Region|
|----|----|
|True && False|/@BEGIN_REGION@and@//@BEGIN_REGION@true@/True/@END_REGION@/ && /@BEGIN_REGION@false@/False/@END_REGION@//@END_REGION@/|
|False &#124;&#124; True|/@BEGIN_REGION@or@//@BEGIN_REGION@false@/False/@END_REGION@/ &#124;&#124; /@BEGIN_REGION@true@/True/@END_REGION@//@END_REGION@/|
|True && (True &#124;&#124; True)|/@BEGIN_REGION@and@//@BEGIN_REGION@true1@/True/@END_REGION@/ && (/@BEGIN_REGION@or@//@BEGIN_REGION@true2@/True/@END_REGION@/ &#124;&#124; /@BEGIN_REGION@true3@/True/@END_REGION@//@END_REGION@/)/@END_REGION@/|
|True && (True &#124;&#124; True)|/@BEGIN_REGION@and@//@BEGIN_REGION@true1@/True/@END_REGION@/ && (/@BEGIN_REGION@or@//@BEGIN_REGION@true2@/True/@END_REGION@/ &#124;&#124; /@BEGIN_REGION@true3@/True/@END_REGION@//@END_REGION@/)/@END_REGION@/|
|True && True &#124;&#124; True|/@BEGIN_REGION@or@//@BEGIN_REGION@and@//@BEGIN_REGION@true1@/True/@END_REGION@/ && /@BEGIN_REGION@true2@/True/@END_REGION@//@END_REGION@/ &#124;&#124; /@BEGIN_REGION@true3@/True/@END_REGION@//@END_REGION@/|
|hayBolitas(Rojo)|/@BEGIN_REGION@hb@/hayBolitas(/@BEGIN_REGION@rojo@/Rojo/@END_REGION@/)/@END_REGION@/|
|nroBolitas(Rojo)|/@BEGIN_REGION@nb@/nroBolitas(/@BEGIN_REGION@rojo@/Rojo/@END_REGION@/)/@END_REGION@/|
|puedeMover(Este)|/@BEGIN_REGION@pm@/puedeMover(/@BEGIN_REGION@este@/Este/@END_REGION@/)/@END_REGION@/|
|siguiente(Este)|/@BEGIN_REGION@sg@/siguiente(/@BEGIN_REGION@este@/Este/@END_REGION@/)/@END_REGION@/|
|previo(Este)|/@BEGIN_REGION@pr@/previo(/@BEGIN_REGION@este@/Este/@END_REGION@/)/@END_REGION@/|
|opuesto(Este)|/@BEGIN_REGION@op@/opuesto(/@BEGIN_REGION@este@/Este/@END_REGION@/)/@END_REGION@/|
|//<br/>// Comentario de lo que devuelve<br/>//<br/>function devolverAlgunValor() {<br/>   Mover(Este)<br/>   return (Rojo)<br/>}<br/><br/><br/>program {<br/>   Poner(devolverAlgunValor())<br/>}<br/>|/@BEGIN_REGION@f1@/<br/>//<br/>// Comentario de lo que devuelve<br/>//<br/>function devolverAlgunValor() {<br/>   /@BEGIN_REGION@mover@/<br/>   Mover(/@BEGIN_REGION@este@/Este/@END_REGION@/)<br/>   /@END_REGION@/<br/>   return (/@BEGIN_REGION@rojo@/Rojo/@END_REGION@/)<br/>}<br/>/@END_REGION@/<br/><br/><br/>/@BEGIN_REGION@program@/<br/>program {<br/>   /@BEGIN_REGION@poner@/<br/>   Poner(/@BEGIN_REGION@cf1@/devolverAlgunValor()/@END_REGION@/)<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|hayFlores_en_(Rojo, Este)|/@BEGIN_REGION@hayF@/hayFlores_en_(/@BEGIN_REGION@rojo@/Rojo/@END_REGION@/, /@BEGIN_REGION@este@/Este/@END_REGION@/)/@END_REGION@/|
|program {<br/>   if (hayFlores_en_(Rojo, Este)) {<br/>      Mover(dondeEsta_(Rojo))<br/>   }<br/>}<br/>|/@BEGIN_REGION@program@/<br/>program {<br/>   /@BEGIN_REGION@if@/<br/>   if (/@BEGIN_REGION@hayF@/hayFlores_en_(/@BEGIN_REGION@rojo1@/Rojo/@END_REGION@/, /@BEGIN_REGION@este@/Este/@END_REGION@/)/@END_REGION@/) {<br/>      /@BEGIN_REGION@mover@/<br/>      Mover(/@BEGIN_REGION@dndE@/dondeEsta_(/@BEGIN_REGION@rojo2@/Rojo/@END_REGION@/)/@END_REGION@/)<br/>      /@END_REGION@/<br/>   }<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|boom("El programa todavía no está completo")|/@BEGIN_REGION@completar@/boom("El programa todavía no está completo")/@END_REGION@/|
|program {<br/>}<br/>|/@BEGIN_REGION@1@/<br/>program {<br/>}<br/>/@END_REGION@/<br/>|
|Poner(Rojo)<br/>|/@BEGIN_REGION@poner@/<br/>Poner(/@BEGIN_REGION@rojo@/Rojo/@END_REGION@/)<br/>/@END_REGION@/<br/>|
|Sacar(Verde)<br/>|/@BEGIN_REGION@sacar@/<br/>Sacar(/@BEGIN_REGION@verde@/Verde/@END_REGION@/)<br/>/@END_REGION@/<br/>|
|Mover(Oeste)<br/>|/@BEGIN_REGION@mover@/<br/>Mover(/@BEGIN_REGION@oeste@/Oeste/@END_REGION@/)<br/>/@END_REGION@/<br/>|
|IrAlBorde(Norte)<br/>|/@BEGIN_REGION@irBorde@/<br/>IrAlBorde(/@BEGIN_REGION@norte@/Norte/@END_REGION@/)<br/>/@END_REGION@/<br/>|
|VaciarTablero()<br/>|/@BEGIN_REGION@vaciar@/<br/>VaciarTablero()<br/>/@END_REGION@/<br/>|
|BOOM("Ingresar motivo...")<br/>|/@BEGIN_REGION@boom@/<br/>BOOM("Ingresar motivo...")<br/>/@END_REGION@/<br/>|
|//<br/>// Un comentario para el procedimiento<br/>//<br/>procedure HacerAlgoConParametros(valor1, otroValor) {<br/>}<br/>|/@BEGIN_REGION@defP@/<br/>//<br/>// Un comentario para el procedimiento<br/>//<br/>procedure HacerAlgoConParametros(valor1, otroValor) {<br/>}<br/>/@END_REGION@/<br/>|
|//<br/>// Desc del procedure<br/>//<br/>procedure HacerAlgo() {<br/>   Poner()<br/>}<br/><br/><br/>program {<br/>   HacerAlgo()<br/>}<br/>|/@BEGIN_REGION@p1@/<br/>//<br/>// Desc del procedure<br/>//<br/>procedure HacerAlgo() {<br/>   /@BEGIN_REGION@poner@/<br/>   Poner()<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/><br/><br/>/@BEGIN_REGION@program@/<br/>program {<br/>   /@BEGIN_REGION@cp1@/<br/>   HacerAlgo()<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|function devolverAlgo() {<br/>   return (Rojo)<br/>}<br/><br/><br/>program {<br/>   Poner(devolverAlgo())<br/>}<br/>|/@BEGIN_REGION@cf1@/<br/>function devolverAlgo() {<br/>   return (/@BEGIN_REGION@rojo@/Rojo/@END_REGION@/)<br/>}<br/>/@END_REGION@/<br/><br/><br/>/@BEGIN_REGION@program@/<br/>program {<br/>   /@BEGIN_REGION@poner@/<br/>   Poner(/@BEGIN_REGION@f1@/devolverAlgo()/@END_REGION@/)<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|function doble(x) {<br/>   return (x + x)<br/>}<br/><br/><br/>program {<br/>   repeat(doble(2)) {<br/>      Poner(Rojo)<br/>   }<br/>}<br/>|/@BEGIN_REGION@f1@/<br/>function doble(x) {<br/>   return (/@BEGIN_REGION@plus@//@BEGIN_REGION@x@/x/@END_REGION@/ + /@BEGIN_REGION@x2@/x/@END_REGION@//@END_REGION@/)<br/>}<br/>/@END_REGION@/<br/><br/><br/>/@BEGIN_REGION@program@/<br/>program {<br/>   /@BEGIN_REGION@repeat@/<br/>   repeat(/@BEGIN_REGION@cf1@/doble(/@BEGIN_REGION@2@/2/@END_REGION@/)/@END_REGION@/) {<br/>      /@BEGIN_REGION@poner@/<br/>      Poner(/@BEGIN_REGION@rojo@/Rojo/@END_REGION@/)<br/>      /@END_REGION@/<br/>   }<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|program {<br/>   if (True) {<br/>      Poner(Rojo)<br/>   }<br/>}<br/>|/@BEGIN_REGION@prog@/<br/>program {<br/>   /@BEGIN_REGION@if@/<br/>   if (/@BEGIN_REGION@true@/True/@END_REGION@/) {<br/>      /@BEGIN_REGION@poner@/<br/>      Poner(/@BEGIN_REGION@rojo@/Rojo/@END_REGION@/)<br/>      /@END_REGION@/<br/>   }<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|program {<br/>   if (True) {<br/>      Poner(Rojo)<br/>   } else {<br/>      Sacar(Verde)<br/>   }<br/>}<br/>|/@BEGIN_REGION@program@/<br/>program {<br/>   /@BEGIN_REGION@if@/<br/>   if (/@BEGIN_REGION@true@/True/@END_REGION@/) {<br/>      /@BEGIN_REGION@poner@/<br/>      Poner(/@BEGIN_REGION@rojo@/Rojo/@END_REGION@/)<br/>      /@END_REGION@/<br/>   } else {<br/>      /@BEGIN_REGION@sacar@/<br/>      Sacar(/@BEGIN_REGION@verde@/Verde/@END_REGION@/)<br/>      /@END_REGION@/<br/>   }<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|program {<br/>   if (puedeMover(Este)) {<br/>      Poner(Rojo)<br/>   } else if (puedeMover(Oeste)) {<br/>      Sacar(Rojo)<br/>   } else if (puedeMover(Sur)) {<br/>   } else {<br/>      Mover(Este)<br/>   }<br/>}<br/>|/@BEGIN_REGION@program@/<br/>program {<br/>   /@BEGIN_REGION@if@/<br/>   if (/@BEGIN_REGION@puedeMover1@/puedeMover(/@BEGIN_REGION@este1@/Este/@END_REGION@/)/@END_REGION@/) {<br/>      /@BEGIN_REGION@poner1@/<br/>      Poner(/@BEGIN_REGION@rojo1@/Rojo/@END_REGION@/)<br/>      /@END_REGION@/<br/>   } else if (/@BEGIN_REGION@puedeMover2@/puedeMover(/@BEGIN_REGION@oeste2@/Oeste/@END_REGION@/)/@END_REGION@/) {<br/>      /@BEGIN_REGION@sacar@/<br/>      Sacar(/@BEGIN_REGION@rojo2@/Rojo/@END_REGION@/)<br/>      /@END_REGION@/<br/>   } else if (/@BEGIN_REGION@puedeMover3@/puedeMover(/@BEGIN_REGION@sur3@/Sur/@END_REGION@/)/@END_REGION@/) {<br/>   } else {<br/>      /@BEGIN_REGION@mover3@/<br/>      Mover(/@BEGIN_REGION@este3@/Este/@END_REGION@/)<br/>      /@END_REGION@/<br/>   }<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|program {<br/>   repeat(5) {<br/>      Mover(Este)<br/>   }<br/>}<br/>|/@BEGIN_REGION@prog@/<br/>program {<br/>   /@BEGIN_REGION@repeat@/<br/>   repeat(/@BEGIN_REGION@5@/5/@END_REGION@/) {<br/>      /@BEGIN_REGION@mover@/<br/>      Mover(/@BEGIN_REGION@este@/Este/@END_REGION@/)<br/>      /@END_REGION@/<br/>   }<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|procedure HacerAlgoCon(x, y) {<br/>}<br/><br/><br/>program {<br/>   HacerAlgoCon(Rojo, Verde)<br/>}<br/>|/@BEGIN_REGION@f1def@/<br/>procedure HacerAlgoCon(x, y) {<br/>}<br/>/@END_REGION@/<br/><br/><br/>/@BEGIN_REGION@prog@/<br/>program {<br/>   /@BEGIN_REGION@f1call@/<br/>   HacerAlgoCon(/@BEGIN_REGION@rojo@/Rojo/@END_REGION@/, /@BEGIN_REGION@verde@/Verde/@END_REGION@/)<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|program {<br/>   Poner_FloresAl_(4, Este)<br/>}<br/>|/@BEGIN_REGION@prog@/<br/>program {<br/>   /@BEGIN_REGION@pf@/<br/>   Poner_FloresAl_(/@BEGIN_REGION@4@/4/@END_REGION@/, /@BEGIN_REGION@este@/Este/@END_REGION@/)<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|program {<br/>   VaciarTablero()<br/>   VaciarTablero()<br/>   VaciarTablero()<br/>}<br/>|/@BEGIN_REGION@p1@/<br/>program {<br/>   /@BEGIN_REGION@v1@/<br/>   VaciarTablero()<br/>   /@END_REGION@/<br/>   /@BEGIN_REGION@v2@/<br/>   VaciarTablero()<br/>   /@END_REGION@/<br/>   /@BEGIN_REGION@v3@/<br/>   VaciarTablero()<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|program {<br/>   x := Rojo<br/>   Poner(x)<br/>}<br/>|/@BEGIN_REGION@prog@/<br/>program {<br/>   /@BEGIN_REGION@asig@/<br/>   x := /@BEGIN_REGION@rojo@/Rojo/@END_REGION@/<br/>   /@END_REGION@/<br/>   /@BEGIN_REGION@poner@/<br/>   Poner(/@BEGIN_REGION@vget@/x/@END_REGION@/)<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|interactive program {<br/>   K_ARROW_LEFT -> {<br/>      Poner(Rojo)<br/>   }<br/>   K_CTRL_ALT_SHIFT_A -> {<br/>      Poner(Verde)<br/>   }<br/>   K_CTRL_SHIFT_1 -> {<br/>      Poner(Azul)<br/>   }<br/>}<br/>|/@BEGIN_REGION@iprog@/<br/>interactive program {<br/>   /@BEGIN_REGION@kb1@/<br/>   K_ARROW_LEFT -> {<br/>      /@BEGIN_REGION@poner1@/<br/>      Poner(/@BEGIN_REGION@rojo1@/Rojo/@END_REGION@/)<br/>      /@END_REGION@/<br/>   }<br/>   /@END_REGION@/<br/>   /@BEGIN_REGION@kb2@/<br/>   K_CTRL_ALT_SHIFT_A -> {<br/>      /@BEGIN_REGION@poner2@/<br/>      Poner(/@BEGIN_REGION@verde2@/Verde/@END_REGION@/)<br/>      /@END_REGION@/<br/>   }<br/>   /@END_REGION@/<br/>   /@BEGIN_REGION@kb3@/<br/>   K_CTRL_SHIFT_1 -> {<br/>      /@BEGIN_REGION@poner3@/<br/>      Poner(/@BEGIN_REGION@azul3@/Azul/@END_REGION@/)<br/>      /@END_REGION@/<br/>   }<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
|interactive program {<br/>   INIT -> {<br/>   Poner(Rojo)<br/>   }<br/>   K_TAB -> {<br/>      Poner(Negro)<br/>   }<br/>   TIMEOUT(500) -> {<br/>   Poner(Verde)<br/>   }<br/>}<br/>|/@BEGIN_REGION@iprogram@/<br/>interactive program {<br/>   INIT -> {<br/>   /@BEGIN_REGION@poner2@/<br/>   Poner(/@BEGIN_REGION@rojo2@/Rojo/@END_REGION@/)<br/>   /@END_REGION@/<br/>   }<br/>   /@BEGIN_REGION@kb1@/<br/>   K_TAB -> {<br/>      /@BEGIN_REGION@poner1@/<br/>      Poner(/@BEGIN_REGION@negro1@/Negro/@END_REGION@/)<br/>      /@END_REGION@/<br/>   }<br/>   /@END_REGION@/<br/>   TIMEOUT(500) -> {<br/>   /@BEGIN_REGION@poner3@/<br/>   Poner(/@BEGIN_REGION@verde3@/Verde/@END_REGION@/)<br/>   /@END_REGION@/<br/>   }<br/>}<br/>/@END_REGION@/<br/>|
|program {<br/>   BOOM("El programa todavía no está completo")<br/>   Poner(Rojo)<br/>}<br/>|/@BEGIN_REGION@completar@/<br/>program {<br/>   /@BEGIN_REGION@comp@/<br/>   BOOM("El programa todavía no está completo")<br/>   /@END_REGION@/<br/>   /@BEGIN_REGION@poner@/<br/>   Poner(/@BEGIN_REGION@rojo@/Rojo/@END_REGION@/)<br/>   /@END_REGION@/<br/>}<br/>/@END_REGION@/<br/>|
