### ISSUE TITLE
Programa Interactivo

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#8]
Gobstones permite crear programas interactivos. Hay que pensar cómo se podrían construir con bloques.

Ejemplo:

```gobstones
interactive program {
  INIT_BLOCK -> { SetupInicial() }
  K_B, K_ESCAPE, K_DELETE, K_BACKSPACE -> { BorrarZonaDeSeleccion() }
  K_0 -> { OperacionAgregarDigitoASeleccion(0) }
  K_1 -> { OperacionAgregarDigitoASeleccion(1) }
   _  -> { OperacionBajarPiezas() }
}
```

* La sintaxis básica no es la misma que con un "program", sino que son múltiples "asociaciones", que son "tecla -> bloque".
* `INIT_BLOCK` es opcional y solo puede ir al principio.
* Hay un bloque default opcional que solo puede ir al final (y que se identifica con `_`)

Las teclas son las dadas por esta gramática:

```
<KEYDEF> → K_(Modifier)?<Key>
<Key> → <UppChar> | <Digit> | <SpecialKey> | <SymbolKey> | <ArrowKey>
<SpecialKey> → SPACE | ENTER | TAB | BACKSPACE | DELETE | ESCAPE
<SymbolKey> → PLUS | MINUS | ASTERISK | SLASH | EQUAL | L_PAREN | R_PAREN | L_ANGLEBR | R_ANGLEBR | L_BRACKET | R_BRACKET
<ArrowKey> → ARROW_LEFT | ARROW_RIGHT | ARROW_UP | ARROW_DOWN
<Modifer> → CTRL_ | ALT_ | SHIFT_ | CTRL_ALT_ | CTRL_SHIFT_
| ALT_SHIFT_ | CTRL_ALT_SHIFT_
```

En [el constructor de bloques de blockly](https://blockly-demo.appspot.com/static/demos/blockfactory/index.html) se puede importar este archivo: [AsociacionDeTecla.txt](https://github.com/Program-AR/gs-element-blockly/files/620451/AsociacionDeTecla.txt) (renombrar a xml) que es un ejemplo de asociación de tecla que puede servir como instrucción para el programa interactivo.

**Comment by afska** [comment]
Hecho en 0.4.0
