### ISSUE TITLE
Cuando un hueco está vacío, el output debe ser siempre vacío

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#80]
Por ejemplo, en el caso de la condición del if, hoy esto:

![seleccion_350](https://user-images.githubusercontent.com/5421992/30608915-3458c338-9d50-11e7-9159-d705a4c02983.png)

Escupe esto:

```Gobstones
  if ('') {
  }
```
y debería escupir esto:

```Gobstones
  if () {
  }
```

Así con todo bloque que tenga un hueco no llenado, sea expresión ó comando.

El objetivo es que de este tipo de errores se encargue el parser de Gobstones, que con otros features que estamos implementando del lado de gs-element-blockly, podremos hacer un mejor informe de errores.

**Comment by fidel-ml** [comment]
Rodri observó con tino que para que esto pueda funcionar, todos los comandos deberían terminar obligatoriamente con punto y coma. Si no, tendrías cosas raras como

a := 1+
Poner(Verde)

y el error sería extrañísimo...

¿No se puede hacer un nivel de análisis de código faltante en Blockly, antes de generar? O sea, que esa asignación chille antes de generar el texto... ¿Se entiende?

**Comment by asanzo** [comment]
Hola, @fidel-ml !

Estoy analizando este issue. Hacer el chequeo de bloque incompleto no es trivial. Hay que ver cuándo se hace. Podemos usar nuestro bloque "completar" y chantarlo en todos lados.

Mientras tanto, de todas formas, hay que analizar qué se escupiría en caso de no haber nada.

Hoy todos los bloques sin completar:

![Selección_013.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/576034cdcf435c0e00215284/125516c66e82c728ace21e0d46db9196268180a02c3ab17cf40ca3d665043761260ea62864c7b96aea1a7d575a564efd475e584caeff892ba4b06e26825458e8c3714d36976345f3e5db55ea43a82a994e82bcbd8f4dc0e83a27e1828e4e3b161755.png)

Escupen:

```Gobstones
procedure HacerAlgo(asdf) {
}

program {
  Poner()
  Sacar()
  Mover()
  IrAlBorde()
  BOOM("Ingresar motivo...")
  HacerAlgo(null)
  if ('') {
  }
  if ('') {
  }
  else {
  }
  repeat('') {
  }
  while (not ('')) {
  }
  nombreDeVariable := hayBolitas()
  nombreDeVariable := puedeMover()
  nombreDeVariable := nroBolitas()
  nombreDeVariable := '' + ''
  nombreDeVariable := '' == ''
  nombreDeVariable :=  &&
  nombreDeVariable := not()
  nombreDeVariable := siguiente()
  nombreDeVariable := previo()
  nombreDeVariable := opuesto()
}
```

Se ve que hay errores (miren el while, los ifs, los repeats, el +, el &&, etc. ¿Qué hago? ¿Les clavo paréntesis a todo lugar donde no haya valor? 

```Gobstones
a := 1 + () 

if(){
}
```

@rodri042 @foones ¿qué se les ocurre que sea mejor para el parser?

**Comment by afska** [comment]
Yo decía de dejar por ejemplo:

a := 1 + ;
if () {
  a := Rojo == ;
  b := not() ;
}

(y terminar toda sentencia con punto y coma más que nada para el primer
caso, que el error sea tipo: "se esperaba otro número pero se obtuvo un fin
de sentencia")

Igual todavía no sé si se lo banca (el punto y coma), que confirme @foones
:P

**Comment by fidel-ml** [comment]
Es mejor () que ('')...
De última, con los identificadores de regiones debería ser fácil indicar
dónde está el error...
No estaría bien poner completar en todos lados, porque su función es otra,
y porque el mensaje de error sería en tiempo de ejecución y no en parsing.
FF

**Comment by asanzo** [comment]
El punto y coma es una gran forma de solucionar algunos problemas, pero no soluciona todos los problemas. ¿qué pasa en este caso?:

![seleccion_015](https://user-images.githubusercontent.com/5421992/32511976-312380c2-c3d4-11e7-94d0-601f2c80a25e.png)

```Gobstones
//opción 1
if( == + ){
}

//opción 2
if( () == () + () ){
}
```

¿Hay alguna mejoría en la detección de errores en alguna de las dos opciones? ¿Hay una mejor opción?

Siento que puedo estar avanzando demasiado. Por ahí sólo con poner espacios vacíos e informar un error de "agujero que falta llenar" ya estamos.

**Comment by afska** [comment]
Claro, y si en vez de generar código tirás una excepción con los id de
bloques con caja vacía? Yo la capturo, los pinto y digo "Hay bloques con
espacios sin completar"

**Comment by fidel-ml** [comment]
El punto y coma ayuda en un montón de lugares, creo (¿@foones?)
Me gusta la opción 2... (con paréntesis). Creo que va a ser más fácil que
encuentre errores, aunque eso debería decirlo @foones...

**Comment by fidel-ml** [comment]
Eso sería mucho mejor: los bloques no dejan generar código si no está todo
completo... Pero esto agregar overhead de chequeo a los bloques, que quizás
sea demasiado.

**Comment by asanzo** [comment]
Por ahora clavé  paréntesis en los vacíos, esperando 2 cosas:

1) descubrir más fácilmente los problemas con los operadores y
2) En un futuro no lejano agregar el chequeo de bloque completo.
