### ISSUE TITLE
"veces" al repetir y "no" por "not"

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#82]
En vez de:

![seleccion_359](https://user-images.githubusercontent.com/5421992/30707257-4e738618-9ed1-11e7-9e16-63eb5680c9ee.png)

Cambiarlo por:

![seleccion_359](https://user-images.githubusercontent.com/5421992/30707297-70259260-9ed1-11e7-8056-d3a32df96438.png)

y en vez de:

![seleccion_360](https://user-images.githubusercontent.com/5421992/30707373-a8935330-9ed1-11e7-8293-94daf03bcba6.png)

Cambiarlo por:

![seleccion_361](https://user-images.githubusercontent.com/5421992/30707464-eea8102c-9ed1-11e7-8390-71cfdb87cc18.png)

@fidel-ml @francofrizzo

**Comment by fidel-ml** [comment]
De acuerdo.
FF
