### ISSUE TITLE
Se podrá hacer que al draguear un bloque, si se va afuera de la pantalla, mueva el foco de la pantalla?

### ISSUE THREAD

**Issue by fidel-ml** [Program-AR/gs-element-blockly#85]

**Comment by asanzo** [comment]
Blockly no deja tocar eso.

Tengo una idea para implementarlo, pero sospecho que me va a llevar **bocha** de tiempo.

Para implementarlo estuve viendo y hay que sobreescribir métodos en block_dragger.js, más específicamente `Blockly.BlockDragger.prototype.dragBlock`, y sus correspondientes `startBlockDrag` y `endBlockDrag` para que esos llamen a los métodos análogos del WorkspaceDragger, e invertir la dirección de dragging para que vaya contra el mouse sólo en el caso de que esté tocando el borde....

Es heavy metal, yo les cargaría en todo caso el issue a los de blockly, si les parece urgente. Igual ya tenemos zoom y collapse, así que somos un poco menos infelices.
