### ISSUE TITLE
Poder quitar "extras" agregados con botón derecho

### ISSUE THREAD

**Issue by afska** [Program-AR/gs-element-blockly#89]
Ahora mismo en el bloque interactivo podés agregar un bloque init y un bloque timeout con botón derecho, y en https://github.com/gobstones/gobstones-web/issues/211 se propone una alternativa para poder sumar "elses" a los bloques alternativa.

El problema de esto es: **una vez agregados, no se pueden borrar**.

Agregar un botón para borrar cada bloque estuve investigando y no encontré forma (parece que blockly no lo soporta).

¿Se te ocurre alguna idea, @asanzo?

**Comment by asanzo** [comment]
@rodri042 lo único que se me ocurre es mirar otros proyectos que juegan con los mutators:

Por ejemplo este:

https://github.com/toebes-extreme/blockly

Permite hacer esto:

![parametrosagregandoysacando](https://user-images.githubusercontent.com/5421992/32182615-dfdec10e-bd75-11e7-8ca4-91e1ace71a31.gif)

(demo [acá](https://pure-object-102213.appspot.com/static/demos/code/index.html))
