### ISSUE TITLE
Sanitización nombres

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#91]

**Comment by asanzo** [comment]
Implementé esto:

![nanaras](https://user-images.githubusercontent.com/5421992/32457871-46d38ece-c309-11e7-80c5-9a43ee09e326.gif)

Escupe:

```Gobstones
procedure ÑáñarasEnElOccipucio() {
}

program {
  ÑáñarasEnElOccipucio()
}
```

También agregué ese chequeo a los parámetros de las funciones y procedimientos, sucede lo mismo.

Y también a la asignación, y de yapa te hice la modificación de los parámetros, @fidel-ml :

![asignacion](https://user-images.githubusercontent.com/5421992/32462245-848b1986-c317-11e7-95be-790a57a31794.gif)

Escupe:

```Gobstones
program {
  color := Rojo
  Dirección_linda := Este
  Poner(color)
  Sacar(color)
  Mover(Dirección_linda)
}
```

Cerrame este issue si te parece que con esto estamos para diciembre, respecto de la sanitización. 

* El problema de los duplicados sigue estando, lo cargué en #92
* Escupir el nombre real del bloque en un pragma lo pateo, como dijimos
* Generé un bug, pero podemos vivir con ello por ahora, creo, en #93

**Comment by asanzo** [comment]
Me faltó testear las variables.

@rodri042 esto se integra en la 0.5.11

@fidel-ml se puede probar en https://program-ar.github.io/gs-element-blockly/

**Comment by fidel-ml** [comment]
Un detalle que vi: las variables, parámetros y funciones deben empezar con
minúscula, como toda expresión no literal.

Por el resto, tengo que sentarme con tranquilidad a verlo...
Gracias, capo!

**Comment by asanzo** [comment]
¿También en el nombre del bloque?

**Comment by fidel-ml** [comment]
Los nombres de procedimientos en Gobstones son siempre con mayúsculas...
FF

**Comment by asanzo** [comment]
Arreglado en 0.5.12

![seleccion_012](https://user-images.githubusercontent.com/5421992/32504558-e1e7449a-c3be-11e7-9ef1-6d097185f897.png)

escupe:  

```Gobstones
program {
  pasaACamel := pasaACamel + 1
}
```

A lo que me refería, Fidel, es a que si le tengo que obligar a escribir con minúscula a quien escrible el nombre del bloque. Como se ve arriba, decidí que no.

**Comment by fidel-ml** [comment]
Ah, perfecto.
Mientras resulte Gobstones compatible. :)
Después veremos los mensajes de error.
FF
