### ISSUE TITLE
Arreglar "else if": ahora tiene que generar "elseif"

### ISSUE THREAD

**Issue by afska** [Program-AR/gs-element-blockly#99]
@fidel-ml por qué el cambio? Solo por curiosidad :stuck_out_tongue: 

Relacionado con https://github.com/gobstones/gobstones-interpreter/pull/26

**Comment by fidel-ml** [comment]
Porque else if genera una irregularidad en la gramática al permitir omitir
llaves, y no expresa adecuadamente el concepto de alternativa múltiple.
